### ISSUE TITLE
Handling bank closing dates in Switzerland

### ISSUE THREAD

**Issue by CasperWSchmidt** [nager/Nager.Date#146]
According to https://www.ubs.com/global/en/bank_for_banks/offering/cash_currency/_jcr_content/par/table.1241980211.file/dGFibGVUZXh0PS9jb250ZW50L2RhbS91YnMvZ2xvYmFsL2JhbmtfZm9yX2JhbmtzL2JhbmtpbmctaG9saWRheXMtc3dpdHplcmxhbmQtMjAxOS5wZGY=/banking-holidays-switzerland-2019.pdf all banks follow the same closing days no matter what county they are in. From the SwitzerlandProvider I can see that many holidays are county-specific.

I could pick a county (fx. CH-ZH) that matches the holidays from UBS, but the code in the provider suggests that christmas eve is not a public holiday (but it is a bank closing day) and St. Stephen's Day is only a public holiday if christmas eve is a sunday (but this year christmas eve is a tuesday but banks are still closed on St. Stephen's Day).

I'm not completely sure how this should be handled. Perhaps a new method in ```DateSystem``` called ```IsBankHoliday``` looking for ```Type == null || Type = PublicHolidayType.Bank``` and then change ```IsPublicHoliday``` to look for ```Type == null || Type = PublicHolidayType.Public```.
Or perhaps another approach is better simply adding year-12-24 and year-12-26 with type ```Bank```?

**Comment by tinohager** [comment]
Should we need this logic in the main library? I think a logic on your site is enough or have you a good reason why we need this logic here?

**Comment by CasperWSchmidt** [comment]
The main library supports different types of holidays, but only has a "single" way of getting all holidays regardless of the type. The function is named GetPublicHolidays but also returns non-public holidays (like bank closing days). If we simply add the new holidays to the provider everyone else using this library will mistakenly get Christmas eve as a public holiday in Switzerland even though it is not (but banks are closed). It is pretty much the same for danish provider even though I didn't recognize this when I submitted the PRs for it back then...

**Comment by tinohager** [comment]
For this we have actually introduced the type if it does not have the flag Public then it is not a global holiday

**Comment by CasperWSchmidt** [comment]
I know, but the method name is GetPublicHolidays which suggests that it should only return public holidays. Therefore I suggest that you either rename it to GetHolidays (perhaps with an optional type parameter) or change the behavior to match the name and introduce other methods to return the other types of holidays.

**Comment by tinohager** [comment]
What you think about `GetPublicHolidays` only return type `Public` and `GetHolidays` return all?

**Comment by CasperWSchmidt** [comment]
Thats fine by me :) But I suggest to either add an optional type parameter to the new method ```GetHolidays``` or create methods similar to ```GetPublicHolidays``` for the other types.

Also, changing the behavior of GetPublicHolidays should IMHO be considered a breaking change so you might want to bump the major version number :)

**Comment by CasperWSchmidt** [comment]
After the recent changes in #264 I believe this issue is really relevant again. The public API in DateSystem.cs is still filled with `GetPublicHolidays` even though it does not only return what is considered public holidays, but really returns ALL holidays (also those flagged as something else). `IsPublicHoliday` however now uses a filter so only holidays flagged as `Public` will yield true. This makes the API inconsistent.

Therefore I suggest renaming `GetPublicHolidays` to `GetHolidays` to make it clear that it returns ALL holidays.

**Comment by CasperWSchmidt** [comment]
Closing to open a new issue about the renaming
