### ISSUE TITLE
Add Hong Kong Public Holidays

### ISSUE THREAD

**Issue by Reena93** [nager/Nager.Date#156]
### Important specifications

* Which country is affected?
* If you have found a mistake please also provide a valid source of your information?

For more information, see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

**Comment by Reena93** [comment]
Hong Kong is having lots of public holidays. Please add it, It will be very hepful

[http://www.1823.gov.hk/common/ical/en.json](url)

**Comment by mkumar341** [comment]
I can do this if no one else is working on it @tinohager

**Comment by tinohager** [comment]
@mkumar341 You are cordially invited to contribute here

**Comment by mkumar341** [comment]
There is one challenge here, how to deal with Statutory holidays? Statutory holidays are only to blue collar jobs or agreement of employment and it is called "Off-in-Lieu"; according to it, if holiday is already rest day(i.e: Sunday) then employer is committed to give off-in-lieu on following day. For example: if Buddha birthday is Sunday then Employer give Monday as holiday to employee.

I was thinking to make it like this:
```
        //Statutory  holiday if on rest day
                if (buddhaBirthday.DayOfWeek == DayOfWeek.Sunday)
                    items.Add(new PublicHoliday(buddhaBirthday.AddDays(1), "佛誕", "Buddha's Birthday", countryCode));
                else
                    items.Add(new PublicHoliday(buddhaBirthday, "佛誕", "Buddha's Birthday (Off-in-Lieu)", countryCode));

```
Just addition of "Off-in-Lieu"

Let me know you advise on it.

**Comment by mkumar341** [comment]
Hi @tinohager , Did you get chance to check it. Waiting for you advise to proceed on this. Thanks :)

**Comment by tinohager** [comment]
@mkumar341 Check the `Shift` method of [DateTimeExtension](https://github.com/tinohager/Nager.Date/blob/master/Src/Nager.Date/Extensions/DateTimeExtension.cs)
