### ISSUE TITLE
Cyprus

### ISSUE THREAD

**Issue by hermesramos** [nager/Nager.Date#158]
**Which country is affected?**
[Cyprus](https://github.com/tinohager/Nager.Date/blob/master/Src/Nager.Date/PublicHolidays/CyprusProvider.cs)

**If you have found a mistake please also provide a valid source of your information?**
Official language is Greek and Turkish -> https://en.wikipedia.org/wiki/Languages_of_Cyprus

### Description

The local language of the holidays is showing in English and some odd characters:

New Year's Day
**Øe?f??e?a**
Clean Monday
Greek Independence Day
Good Friday
Cyprus National Day?
Easter Monday
Easter Tuesday
Labour Day
Pentecost
Dormition of the Theotokos
Cyprus Independence Day
Greek National Day
Christmas Eve
Christmas Day
St. Stephen's Day

**Comment by tinohager** [comment]
Can you add the correct translation?

**Comment by hermesramos** [comment]
That's what I have for now:

English -> https://www.timeanddate.com/calendar/custom.html?year=2019&country=94&lang=en&lang2=0&cdt=1&typ=0&display=3&df=1
Greek -> https://www.timeanddate.com/calendar/custom.html?year=2019&country=94&lang2=0&cdt=1&typ=0&display=3&df=1
Turkish -> https://www.timeanddate.com/calendar/custom.html?year=2019&country=94&cdt=1&typ=0&display=3&df=1

Hope it helps. Please let me know if you need additional help, I will try to get additional sources.
