### ISSUE TITLE
IsPublicHoliday is false for Columbus Day 2018 (US) in Full Framework.

### ISSUE THREAD

**Issue by lusham** [nager/Nager.Date#174]
USA, 8th of October 2018 is Columbus Day (second Monday in October)

`DateSystem.GetPublicHoliday(2018, CountryCode.US)` returns it as part of the list but `DateSystem.IsPublicHoliday` returns false:

```
var columbusDay = DateSystem.GetPublicHoliday(2018, CountryCode.US).ToList()[6];
var isHoliday = DateSystem.IsPublicHoliday(columbusDay.Date, CountryCode.US); // false
```
The issue is when project targets Full Framework - no issue with .Net Core target.

**Comment by tinohager** [comment]
Columbus Day is not a full Holiday is only a holiday in some counties. I have check with different TargetFrameworks with no problems.

**Comment by tinohager** [comment]
https://ci.appveyor.com/project/tinohager/nager-date/builds/30035487
