### ISSUE TITLE
Add ActualDate Property to PublicHoliday

### ISSUE THREAD

**Issue by Smoles** [nager/Nager.Date#176]
It would be useful to know the actual date of the Holiday and not just the date on which it's observed. It would be nice if the PublicHoliday object had a property such as ActualDate (maybe there's a better name for it).

**Comment by tinohager** [comment]
[UnitedStatesProvider.cs](https://github.com/tinohager/Nager.Date/blob/master/Src/Nager.Date/PublicHolidays/UnitedStatesProvider.cs) you spoke about shifts? Or what do you mean with ActualDate?

**Comment by Smoles** [comment]
So it's my understanding that the PublicHoliday.Date property represents the Observed date for that Holiday. For example, if Christmas lands on a Sunday it's shifted to Monday. But it would be useful to also know the actual date of the holiday. So if we took the Christmas example again PublicHoliday.ActualDate would be December 25th of that year.

PublicHoliday.Date = 12/26/2016
PublicHoliday.ActualDate = 12/25/2016

Like I said, maybe ActualDate is not the best name for the property.

**Comment by rkalasky** [comment]
This would be extremely helpful for my use case as well.

Something like this:
```
var christmasDay = new DateTime(year, 12, 25)
var shiftedChristmasDay = christmasDay.Shift(saturday => saturday.AddDays(-1), sunday => sunday.AddDays(1));
items.Add(new PublicHoliday(christmasDay, shiftedChristmasDay, "Christmas Day", "Christmas Day", countryCode));
```
In many cases, the date would be the same but it would allow the consumer to choose which date they want. If we're just wanting to display holidays on a calendar, the original date is needed. If we're looking at "work days", the shifted date is needed.

**Comment by rkalasky** [comment]
Looking through the different region implementations, it seems like it's inconsistent whether we shift or not. We would really only need to change places that use the `Shift` function today. The default PublicHoliday constructor could remain and just assign the same date to the Shifted and Actual date properties.

**Comment by ericbayperez** [comment]
@tinohager I could implement what @rkalasky suggested if you are okay with this change.

**Comment by tinohager** [comment]
@ericbayperez  Can you give me a suggestion on how you plan to implement it?

**Comment by ericbayperez** [comment]
1. Add an ActualDate to the PublicHoliday class.

2. Change the existing PublicHoliday constructors to set PublicHoliday.ActualDate to the same value that PublicHoliday.Date is being set to.

3. Add a new PublicHoliday constructor that accepts "actualDate" and sets the PublicHoliday.ActualDate to be actualDate.

4. In UnitedStatesProvider.cs, if we shift a holiday, we should save DateTimes before we shift and after we shift, then pass those into the constructor as date and actualDate.

**Comment by tinohager** [comment]
@ericbayperez I wan`t not duplicate the date in the constructor i will check this issue the next days...

**Comment by jbroudou** [comment]
Hi, 
What's the status regarding this improvement? Are there still plans to introduce an Actual date?

**Comment by tinohager** [comment]
At the moment it is not planned
