### ISSUE TITLE
Croatia Statehood Day date changed

### ISSUE THREAD

**Issue by miblazevic** [nager/Nager.Date#190]
Croatia has changed the date of "Statehood Day" / "Dan državnosti" from June 25. to May 30.

More about it here:  https://en.wikipedia.org/wiki/Public_holidays_in_Croatia

Not sure how to handle this one. Maybe an EndYear param should be introduced?

**Comment by tinohager** [comment]
Check this implementation https://github.com/tinohager/Nager.Date/blob/62fafedca53caeefa1c9bd16f0d79970ac24195e/Src/Nager.Date/PublicHolidays/GermanyProvider.cs#L117

**Comment by miblazevic** [comment]
This should do. https://github.com/tinohager/Nager.Date/pull/191

**Comment by tinohager** [comment]
Thanks for the pr
