### ISSUE TITLE
Brazil Carnival

### ISSUE THREAD

**Issue by dimmuboy** [nager/Nager.Date#194]
### Important specifications

Brazil
https://www.officeholidays.com/countries/brazil/2020
https://www.officeholidays.com/holidays/brazil/brazil-carnival

### Description

Why is 24th February 2020 is not present? It's a bank holiday too.

![image](https://user-images.githubusercontent.com/12607479/75330764-dbcea580-5881-11ea-83ec-7825ee5ef915.png)

**Comment by tinohager** [comment]
I can not found Carnival on wikipedia, the main source for this project is the wikipedia page  https://en.wikipedia.org/wiki/Public_holidays_in_Brazil

**Comment by dimmuboy** [comment]
So it's look like wikipedia is wrong. I mean that I can more believe to Central bank of Brazil and my brazil colleagues.
We have few projects in UiPath that depends on Nager.Date and it fails because tried to find rates data in bank website on holiday :/
It will be great if you can fix it.

**Comment by tinohager** [comment]
I would add the additional tag immediately if Wikipedia accepts the change. It is not possible to collect the holidays for each country on different websites. I hope you can understand this.

**Comment by dimmuboy** [comment]
I'm sorry but I can't understand. Why you need some confirmation from wikipedia page when 25th Feb is not on wiki too but in your public holidays list it is?
BTW Brazil Central bank is much more relevant than some wikipedia page.

**Comment by laloune** [comment]
personally I understand @tinohager since the information has to be unified (this is so to say the goal of his api)

just change wikipedia according to your source like I did in the past in the issue #84
