### ISSUE TITLE
Switzerland - December 26th - St Stephen's Day

### ISSUE THREAD

**Issue by klamir051** [nager/Nager.Date#197]
St Stephen's Day / Stephanstag / Zweiter Weihnachtstag is not present on the Swiss public holidays list.

See for reference: https://en.wikipedia.org/wiki/Public_holidays_in_Switzerland

**Comment by tinohager** [comment]
Thanks for reporting. I think the problem is we have here a ruel for canton `Neuchâtel` for all cantons. I fix this.

https://github.com/nager/Nager.Date/blob/master/Src/Nager.Date/PublicHolidays/SwitzerlandProvider.cs

**Comment by klamir051** [comment]
Works like a charm, thank you!
