### ISSUE TITLE
DateSystem.GetPublicHoliday(string, int)' is obsolete

### ISSUE THREAD

**Issue by netmajor** [nager/Nager.Date#200]
Hi,
When I add this line of code in .Net Core app:

`            IEnumerable<PublicHoliday> PublicHolidays() => DateSystem.GetPublicHoliday("PL", todayYear);`

I get warning:

> 'DateSystem.GetPublicHoliday(string, int)' is obsolete: 'Use GetPublicHoliday instead, the sorting of the parameters was changed'	

Please update documentation to new usage of library

**Comment by tinohager** [comment]
Hi, i have update the documentation. I think now it should fit.

**Comment by netmajor** [comment]
Thanks!
