### ISSUE TITLE
Public holiday for (Northern Ireland, Walse & Scotland )

### ISSUE THREAD

**Issue by letoncse** [nager/Nager.Date#203]
### Important specifications

* Which country is affected?
(Northern Ireland, Walse & Scotland)
I'm not getting holiday for (Northern Ireland, Walse & Scotland ). How can i get those region public holidays?

**Comment by tinohager** [comment]
You found this Informations in the [UnitedKingdomProvider](https://github.com/nager/Nager.Date/blob/master/Src/Nager.Date/PublicHolidays/UnitedKingdomProvider.cs) set a filter by Counties
