### ISSUE TITLE
Assembly does not have a strong name

### ISSUE THREAD

**Issue by fszewczy** [nager/Nager.Date#204]
Is it possible for the library to be signed? Adding Nager.Date to project using Nuget causes a warning:

> Warning	CS8002	Referenced assembly 'Nager.Date, Version=1.25.11.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

**Comment by tinohager** [comment]
If you need the DLL signed then I ask you to sign it yourself. I do not want to deal with this topic at the moment.

**Comment by fszewczy** [comment]
OK, understandable.
