### ISSUE TITLE
IsPublicHoliday is returning true even when it is not public

### ISSUE THREAD

**Issue by kimdv** [nager/Nager.Date#206]
### Important specifications

* Which country is affected? DK
* If you have found a mistake please also provide a valid source of your information?

For more information, see the `CONTRIBUTING` guide.

### Description

I use `new DateTime(2020, 05, 22)` that is an `Bank, School, Optional` holiday. Thus not an `Public`. 
But using ` DateSystem.IsPublicHoliday()` return true. 

The API is a bit confusing I think

**Comment by tinohager** [comment]
i have push a update can you check again
