### ISSUE TITLE
How to get Holidays per Region in Germany?

### ISSUE THREAD

**Issue by jogibear9988** [nager/Nager.Date#208]
In germany, not all Regions  have the same Holiday:

https://en.wikipedia.org/wiki/Public_holidays_in_Germany

even some cities have special ones.

How can I use: DateSystem.IsPublicHoliday(currentDate, CountryCode.DE) ?

**Comment by tinohager** [comment]
There is no function avaiable for this case. You can get all Holidays and check the result with the county code.

**Comment by jogibear9988** [comment]
And how do I get the Holidays wich are only in some citys/region?

**Comment by tinohager** [comment]
Load all holidays from the country and filter the result with linq?
