### ISSUE TITLE
Search supporters

### ISSUE THREAD

**Issue by tinohager** [nager/Nager.Date#211]
Hi I have recently moved the project to an organization account. I would be happy if there are people in the community who want to support this project. My goal is to find a group of people in the long run who will continue the project with me.

We have different tasks:

- Maintenance of the existing countries
- Adding new countries
- Expansion of the website (vue.js)
- Extension of the API (asp .net core)

If you feel addressed then simply let me know here.

**Comment by samtrion** [comment]
I would like to offer my support.

**Comment by HayriPV** [comment]
I'd like to help. Can we discuss further?

**Comment by tinohager** [comment]
Hello HayriPV
Can you join our Slack channel?
https://join.slack.com/t/nagerat/shared_invite/zt-q8h58u5x-Av30JgWXY9Utrlal4LvdCA

**Comment by CasperWSchmidt** [comment]
My time is limited, but I think this library is really nice so I would like to contribute whatever I can :)
