### ISSUE TITLE
Set holidays and get vaccation dates

### ISSUE THREAD

**Issue by Headstrike** [nager/Nager.Date#212]
_Affects germany_

I have two ideas for implementation.

**Idea 1:**
It is possible to set specific Holidays such as 24.12, 31.12 and Mariä Himmelfahrt in Germany. 
Because sometimes 24.12 and 31.12 is half a holiday and Mariä Himmelfahr only is a holiday in parts of Bayern.
It would be great if I coud set "mariaehimmelfahrt,heiligabend or silvester to true.

**Idea 2:**
I can set my vaccation time for example "20.12.2020 - 06.01.2021" and I get the days of vaccation i have to book minus weekends and holidays.

Kindest regards

**Comment by tinohager** [comment]
We would like to focus only on holidays that apply to entire states. Otherwise, the topic becomes too complex.
