### ISSUE TITLE
2020-08-31 - CountryCode.GB - returning false (IsPublicHoliday)

### ISSUE THREAD

**Issue by winglessraven** [nager/Nager.Date#213]
### Important specifications

* Which country is affected?
GB

* If you have found a mistake please also provide a valid source of your information?
Shows as a holiday on https://date.nager.at/PublicHoliday/Country/GB but DateSystem.IsPublicHoliday(new DateTime(2020,08,31), CountryCode.GB) returns false.

For more information, see the `CONTRIBUTING` guide.

### Description

2020-08-31 is a public holiday in GB - date.nager.at shows it correctly but in a C# application the IsPublicHoliday method is returning false

**Comment by winglessraven** [comment]
Changing to use IsOfficialPublicHolidayByCounty - appears that because GB-SCT doesn't have this holiday it returns false.

**Comment by blunners** [comment]
Hey, can we re-open this please as `IsOfficialPublicHolidayByCounty` is marked as obsolete and `DateSystem.IsPublicHoliday(new DateTime(2020,08,31), CountryCode.GB)` still returns false.

Thanks!
