### ISSUE TITLE
Is there support for the variation of public holidays between US states?

### ISSUE THREAD

**Issue by GreySage** [nager/Nager.Date#217]
### Important specifications
USA
### Description
For example, Delaware does not celebrate presidents day (3rd Monday in February) but DOES celebrate Good Friday. Using this library in such a state will cause problems.

**Comment by tinohager** [comment]
Yes we have a [Counties field](https://github.com/nager/Nager.Date/blob/35873990b4c7a7738daf862a4a111c49dd4c58c6/Src/Nager.Date/Model/PublicHoliday.cs#L37)
https://github.com/nager/Nager.Date/blob/35873990b4c7a7738daf862a4a111c49dd4c58c6/Src/Nager.Date/PublicHolidays/UnitedStatesProvider.cs#L59
