### ISSUE TITLE
Unmerged Holiday information (GB, 2022+23, New Year's Day)

### ISSUE THREAD

**Issue by MaxWorno** [nager/Nager.Date#218]
Is there any reason why there are two separate holiday entries for _New Year's Day_ for _GB_ in both 2022 and 2023 or should this be merged?

See entries with index 1 and 2 in [https://date.nager.at/api/v2/PublicHolidays/2022/GB](url) and [https://date.nager.at/api/v2/PublicHolidays/2023/GB](url). All entries (apart from the mergeable counties) seem to coincide.

**Comment by tinohager** [comment]
This is only is the holiday on a weekend
https://github.com/nager/Nager.Date/blob/2a2091085656103982ad6237b46fbe561bc82cc1/Src/Nager.Date/PublicHolidays/UnitedKingdomProvider.cs#L44
