### ISSUE TITLE
New non-working day in Croatia

### ISSUE THREAD

**Issue by newsjj** [nager/Nager.Date#219]
Country affected : 
     Croatia

Must insert new non-working day : 18.11.2020
link:
https://www.zakon.hr/z/372/Zakon-o-blagdanima,-spomendanima-i-neradanim-danima-u-Republici-Hrvatskoj

Best regards

**Comment by tinohager** [comment]
@newsjj What is the name of the new holiday?

**Comment by newsjj** [comment]
Dan sjećanja na žrtve Domovinskog rata i Dan sjećanja na žrtvu Vukovara i
Škabrnje
or
english:
Remembrance Day for the victims of the Homeland War and Remembrance Day for
the victims of Vukovar and Škabrnja


br

**Comment by obarscan** [comment]
will be released an update on time?

**Comment by tinohager** [comment]
Can anyone send a PR?

**Comment by sigismund** [comment]
I think this was already added @ [c2deaa2c366503a6e8786dc49bb4b7259c3cbbf3](https://github.com/nager/Nager.Date/commit/c2deaa2c366503a6e8786dc49bb4b7259c3cbbf3#diff-a09924676030724375a1497aa51b6fbeb50fae6ea6ab9d67effe49851186e653)

**Comment by tinohager** [comment]
https://github.com/nager/Nager.Date/blob/4ae81585754dc034b5685bfcedf0c19a4448c9d0/Src/Nager.Date/PublicHolidays/CroatiaProvider.cs#L89

**Comment by tinohager** [comment]
Maybe this is wrong, `year >= 2020` ?

https://github.com/nager/Nager.Date/blob/4ae81585754dc034b5685bfcedf0c19a4448c9d0/Src/Nager.Date/PublicHolidays/CroatiaProvider.cs#L87

**Comment by tinohager** [comment]
Can you please check the changes
