### ISSUE TITLE
Update Croatian holidays

### ISSUE THREAD

**Issue by filipvi** [nager/Nager.Date#222]
Croatia (HR)

Hi,
There are some changes in public holidays in Croatia so if you can update your package.

Added:
**30.05.2020**  Dan državnosti (National Day)
**18.11.2020**  Dan sjećanja na žrtve Domovinskog rata i Dan sjećanja na žrtvu Vukovara i Škabrnje (Remembrance Day for the victims of the Homeland War and Remembrance Day for the victims of Vukovar and Škabrnja)

_Notes:_
18.11.2020 (if year >= 2020)

Thanks in advance.

**Comment by tinohager** [comment]
Duplicate https://github.com/nager/Nager.Date/issues/219 ?

**Comment by filipvi** [comment]
Yes, correct if statement would be:
if (year >= 2020){
 ... ...
}

For both holidays (National Day and Remembrance Day)

**Comment by tinohager** [comment]
Can you please check the changes

**Comment by filipvi** [comment]
I is okay now. Thanks a lot.

**Comment by tinohager** [comment]
Thanks
