### ISSUE TITLE
Update UK holidays for 2022 in line with announced Jubilee holidays

### ISSUE THREAD

**Issue by markjritchie** [nager/Nager.Date#223]
### Jubliee Holidays in the UK in 2022

In the UK the May Bank Holiday Weekend will be moved to Thursday 2 June and an additional Bank Holiday on Friday 3 June

### Description
For 2022 The May Bank Holiday should return 2nd June and an extra holiday added on the 3rd June. Note this is just for 2022.

### Citation:
https://www.gov.uk/government/news/extra-bank-holiday-to-mark-the-queens-platinum-jubilee-in-2022

**Comment by tinohager** [comment]
Is this the `Early May Bank Holiday`?

https://github.com/nager/Nager.Date/blob/4ae81585754dc034b5685bfcedf0c19a4448c9d0/Src/Nager.Date/PublicHolidays/UnitedKingdomProvider.cs#L80

**Comment by markjritchie** [comment]
No it's this one:

  items.Add(new PublicHoliday(lastMondayInMay, "Spring Bank Holiday", "Spring Bank Holiday", countryCode, 1971));

**Comment by tinohager** [comment]
Can you please check the changes

**Comment by markjritchie** [comment]
Looks good, I'll run some unit tests against it when the package is published

**Comment by stevieTheCoder** [comment]
@markjritchie Could you confirm whether this change been published?

**Comment by markjritchie** [comment]
Yes it is
