### ISSUE TITLE
Bug with the Jubilee change

### ISSUE THREAD

**Issue by markjritchie** [nager/Nager.Date#224]
### Important specifications

Bug in the GB provider

### Description

The date at line 117 should be the 3rd of June, sorry for not picking that up when I reviewed the commit. I did attempt to create a PR for it but don't have permissions unfortunately. 

[See the double entry of 2 June rather than the 2nd and 3rd](https://date.nager.at/PublicHoliday/Country/GB/2022)

**Comment by tinohager** [comment]
[GitHub Standard Fork & Pull Request Workflow](https://gist.github.com/Chaser324/ce0505fbed06b947d962)
