### ISSUE TITLE
Australia Boxing day

### ISSUE THREAD

**Issue by yannickk** [nager/Nager.Date#225]
### Which country is affected?
Australia

### The source of the information?

https://date.nager.at/PublicHoliday/Country/AU

### Description

Boxing day on Monday is not being detected as a public holiday. i.e. whilst boxing day is the 26/12/2021 and falls on a Saturday, this usually means we have the following Monday as a public holiday (28/12/2021)

**Comment by tinohager** [comment]
https://github.com/nager/Nager.Date/blob/master/Src/Nager.Date/PublicHolidays/AustraliaProvider.cs

**Comment by tinohager** [comment]
Is this a public rule in all counties?
`*If a Public Holiday falls on a Saturday or Sunday, the following Monday is also observed as a Public Holiday`

**Comment by yannickk** [comment]
Hi Tino,

This rule applies to national public holidays (state holidays may be
different). Another example of it occurring was Australia Day 2020 where
the 26th of January was a Sunday so the following Monday was a public
holiday.

**Comment by tinohager** [comment]
@yannickk the new version is available
