### ISSUE TITLE
CSV unavailable (leads to 404)

### ISSUE THREAD

**Issue by MalPhunktion** [nager/Nager.Date#226]
### Which country is affected?
Problem seems to be present on all countries.

### The source of the information?
For example:
https://date.nager.at/PublicHoliday/Country/DE/2020/CSV
https://date.nager.at/PublicHoliday/Country/AT/2020/CSV
and more (also previous years no longer available)

### Description
The CSV download button unfortunately leads to a 404 page and seems to occur on all countries and year.

**Comment by laloune** [comment]
the new API endpoint is https://date.nager.at/api/v2/publicholidays/

I think that the old one is deprecated (correct me if I'm wrong @tinohager)

**Comment by tinohager** [comment]
i check this tonight this is a bug

**Comment by MalPhunktion** [comment]
> i check this tonight this is a bug

Thanks for the information. Will sit back and wait until you have some more information available.

**Comment by MalPhunktion** [comment]
Thanks for the quick fix, all seems to be working again.
