### ISSUE TITLE
Local holidays in Brasil

### ISSUE THREAD

**Issue by diegobrum** [nager/Nager.Date#229]
### Which country is affected?

Brasil

### The source of the information?

https://pt.wikipedia.org/wiki/Feriados_no_Brasil (Local holidays)

### Description

Add all local holidays in Brasil response

**Comment by tinohager** [comment]
I would be very happy if you would add the missing data.

**Comment by tinohager** [comment]
Thanks for the implementation. Since it also changes the structure I would like to check the change in detail after Christmas. I hope this is ok for you....

**Comment by diegobrum** [comment]
Sure :)

No problema at all

Have a great xmas
