### ISSUE TITLE
County API

### ISSUE THREAD

**Issue by wolkenschieber** [nager/Nager.Date#232]
The holidays are resolved to county level. However the counties are enumerated in ISO 3166-2 format: 
```
{
    "date": "2021-01-06",
    "localName": "Heilige Drei Könige",
    "name": "Epiphany",
    "countryCode": "DE",
    "fixed": true,
    "global": false,
    "counties": [
      "DE-BW",
      "DE-BY",
      "DE-ST"
    ],
    "launchYear": 1967,
    "type": "Public"
  }
```
For further processing, a resolution from ISO 3166-2 token to name would be useful, eg `DE-BY` -> `Bayern`.

This could be implemented in an endpoint like `/Api/v2/CountyInfo/{countryCode}`, which lists a country and its counties with token and name.

**Comment by tinohager** [comment]
For this we would again need a lot of translations for various languages. Maybe i add this logic to my [country project](https://github.com/nager/Nager.Country).
