### ISSUE TITLE
time limit on docker

### ISSUE THREAD

**Issue by guyko81** [nager/Nager.Date#233]
Hi,

I think I caused this issue with over-usage of the API, and I sincerely apologise for it! That was not my intention, I didn't really think it through, nor read the readme thoroughly...
But it seems that the docker version inherited the time limit from the latest change on the API. Obviously a previous version works just fine:
docker pull nagerat/nager-date:447009654470e82f3f62f0ed87dcd60d1e185f16

Is it possible to separate the 2 behaviours and let the docker version work without time limit?

Thanks and really sorry again!

**Comment by tinohager** [comment]
Hi, on the docker image i remove this protection. It is only for the public ip. There are already more people who feel addressed :)

**Comment by guyko81** [comment]
a bit of a relief that I'm not the only one who don't read :)
thanks for the resolution!

**Comment by guyko81** [comment]
👍 thank you!
