### ISSUE TITLE
Public API IpRateLimiting now active

### ISSUE THREAD

**Issue by tinohager** [nager/Nager.Date#234]
Hi all, I have now enabled IpRateLimiting on the public API. If the accesses are not enough for you then please use the Docker image.

**Comment by laloune** [comment]
Hello,

thanks for the information. Can you please give us a short hint what the rates are ?

**Comment by tinohager** [comment]
"GeneralRules": [
{
"Endpoint": "*",
"Period": "1s",
"Limit": 10
},
{
"Endpoint": "*",
"Period": "1h",
"Limit": 100
}
]

**Comment by mblaschke** [comment]
Any possibility to relax the hour limit a little bit?

I'm the maintainer of https://github.com/webdevops/public-holiday-exporter and just added a caching mechanism to not requesting your API at runtime anymore. But for a short timeframe this might need more requests.

Maybe 250 per hour and set the limit per day to 2400 requests? Or is this just too much?

**Comment by tinohager** [comment]
@mblaschke Your project is also a Docker container, wouldn't it be possible to use the Docker container from us? What I could imagine would be api keys on which I turn off the limit.
