### ISSUE TITLE
Git tags haven't been produced in a while

### ISSUE THREAD

**Issue by nmbro** [nager/Nager.Date#250]
### Which country is affected?

None.

### The source of the information?

https://github.com/nager/Nager.Date/tags
![image](https://user-images.githubusercontent.com/3308346/108686446-bb1d4800-74f5-11eb-848e-b56956b166f1.png)

### Description

Git tags / Releases haven't been produced in a while - this makes it difficult to compare changes between 2 versions directly in Github.

**Comment by tinohager** [comment]
We have switch to this file https://github.com/nager/Nager.Date/blob/master/CHANGELOG.md

**Comment by nmbro** [comment]
The change that got me worried was this ambiguous Changelog statement `Fix Docker Container crash`

So I wanted to figure out exactly what fix, or rather exactly what crashing, but I see now that you are publishing `Nager.Date.Website.csproj` through this repo, so I'm guessing it relates to that?

If that's true could you be a little more specific "Fixed Nager public website docker crash"?

**Comment by nmbro** [comment]
🤦 oh you can actually host the api yourself - excuse my ignorance.

**Comment by tinohager** [comment]
Missing culture dependencies

https://github.com/nager/Nager.Date/commit/87f069ced2cab2356c9aab72ff904261ad94bdca#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557

**Comment by nmbro** [comment]
Thanks for taking your time to answer my questions

**Comment by tinohager** [comment]
you are welcome
