### ISSUE TITLE
Add Turkey religious holidays (Feast of Ramadan & Feast of Eid)

### ISSUE THREAD

**Issue by alibekdas** [nager/Nager.Date#255]
### Which country is affected?

Turkey (TR)

### The source of the information?

https://www.timeanddate.com/holidays/turkey/sacrifice-feast#:~:text=The%20Sacrifice%20Feast%20is%20one,days%20after%20the%20Ramadan%20Feast.

### Description

religious holidays additional

**Comment by tinohager** [comment]
I have already looked at this once but there is no fixed date for this holiday. As far as I have read in here, the holidays depend on the moon visibility. Therefore I have not implemented this.

**Comment by samtrion** [comment]
We generally do not have an implementation based on the Hijiri Calendar yet. Therefore we ask for some more patience.

**Comment by ali-bekdas** [comment]
Yes that’s right.  Ramadan and Eid are depend on Hijri calendar and Hijri calendar has less day than Gregorian calendar in a year. Therefore these holidays can be found by a calculation.

Hijri Calendar

//TR: Ramazan Bayramı Arifesi
//EN: Ramadan Holiday Eve
30 Ramadan (Hijri Calendar)
//TR: Ramazan Bayramı 1. Gün
//EN: Ramadan Holiday First Day
1 Sevval (Hijri Calendar)
//TR: Ramazan Bayramı 3. Gün
//EN: Ramadan Holiday Second Day
2 Sevval (Hijri Calendar)
//TR: Ramazan Bayramı 2. Gün
//EN: Ramadan Holiday Third Day
3 Sevval (Hijri Calendar)

//TR: Kurban Bayramı Arifesi
//EN: Eid Holiday Eve
9 Zilhicce (Hijri Calendar)
//TR: Kurban Bayramı 1. Gün
//EN: Eid Holiday First Day
10 Zilhicce (Hijri Calendar)
//TR: Kurban Bayramı 2. Gün
//EN: Eid Holiday Second Day
11 Zilhicce (Hijri Calendar)
//TR: Kurban Bayramı 3. Gün
//EN: Eid Holiday Third Day
12 Zilhicce (Hijri Calendar)
//TR: Kurban Bayramı 4. Gün
//EN: Eid Holiday Fourth Day
13 Zilhicce (Hijri Calendar)

Gregorian & Hijri Calendar => https://www.islamicfinder.org/islamic-calendar/2021/April/?type=Gregorian&language=tr


In addition, 28 October is half day holiday in Turkey. Can you add it?

//TR: Cumhuriyet Bayramı Arifesi
//EN: Republic Day Eve
28 October

**Comment by ali-bekdas** [comment]
Add pull request.
https://github.com/nager/Nager.Date/pull/256
