### ISSUE TITLE
Add Hong Kong public Holidays

### ISSUE THREAD

**Issue by HayriPV** [nager/Nager.Date#258]
### Which country is affected?
 Hong Kong HK

### The source of the information?

https://publicholidays.hk/2021-dates/

https://www.qppstudio.net/publicholidays2021/hong_kong.htm

### Description

Public holidays for Hong Kong are missing

1 Jan | Fri | New Year's Day
12 Feb | Fri | Lunar New Year
13 Feb | Sat | The Second Day of Lunar New Year
14 Feb | Sun | The Third Day of Lunar New Year
15 Feb | Mon | The Fourth Day of Lunar New Year
2 Apr | Fri | Good Friday
3 Apr | Sat | The Day Following Good Friday
4 Apr | Sun | Ching Ming Festival
5 Apr | Mon | Easter Monday
5 Apr | Mon | The Day Following Ching Ming Festival
6 Apr | Tue | The Day Following Easter Monday
1 May | Sat | Labour Day
19 May | Wed | Birthday of Buddha
14 Jun | Mon | Tuen Ng Festival
1 Jul | Thu | HKSAR Establishment Day
22 Sep | Wed | The Day Following Mid-Autumn Festival
1 Oct | Fri | National Day
14 Oct | Thu | Chung Yeung Festival
25 Dec | Sat | Christmas Day
27 Dec | Mon | The First Weekday After Christmas Day

**Comment by tinohager** [comment]
@HayriPV This is a duplicate, check this issue https://github.com/nager/Nager.Date/issues/156
