### ISSUE TITLE
Some Holidays not listed for specific counties

### ISSUE THREAD

**Issue by bensh90** [nager/Nager.Date#260]
### Which country is affected?

DE

### The source of the information?

Selftest

### Description

The following bug was found:

I used the following code in my test program. I Expected TH to be in the result but it wasn't, even though corpus Christi is a holiday in some parts of TH. I used this list as reference for identifing holidays. https://de.wikipedia.org/wiki/Gesetzliche_Feiertage_in_Deutschland

I assume that this bug will involve other "counties" as well.

```
DateTime date = new DateTime(2021, 6, 3);
DateTime date2 = new DateTime(2021, 6, 3);
var dates = DateSystem.GetPublicHolidays(dateVon, dateBis).Where(x => x.CountryCode == CountryCode.DE);
```

to fix this problem, i guess the results would have to be split into postal codes in certain regions. The question is, if such a detailed result is intended or not

**Comment by tinohager** [comment]
Such a detailed return is not planned at the moment. Since we would have to go into great detail here. And covering it worldwide would be an enormous effort. Sorry

**Comment by bensh90** [comment]
I thought as much, but it was worth a try, But since it would have been for an "important" piece of software, we can't use it like this then. Such a pity. But its okay, thanks anyway and have a good day
