### ISSUE TITLE
Add Good Friday in the US Holidays

### ISSUE THREAD

**Issue by salmissira** [nager/Nager.Date#273]
The list of US Holidays does not include good friday, can these be included?

Response bodyDownload[   {     "date": "2021-01-01",     "localName": "New Year's Day",     "name": "New Year's Day",     "countryCode": "US",     "fixed": false,     "global": true,     "counties": null,     "launchYear": null,     "type": "Public"   },   {     "date": "2021-01-18",     "localName": "Martin Luther King, Jr. Day",     "name": "Martin Luther King, Jr. Day",     "countryCode": "US",     "fixed": false,     "global": true,     "counties": null,     "launchYear": null,     "type": "Public"   },   {     "date": "2021-01-20",     "localName": "Inauguration Day",     "name": "Inauguration Day",     "countryCode": "US",     "fixed": true,     "global": false,     "counties": [       "US-DC",       "US-LA",       "US-MD",       "US-VA"     ],     "launchYear": null,     "type": "Public"   },   {     "date": "2021-02-15",     "localName": "Presidents Day",     "name": "Washington's Birthday",     "countryCode": "US",     "fixed": false,     "global": true,     "counties": null,     "launchYear": null,     "type": "Public"   },   {     "date": "2021-05-31",     "localName": "Memorial Day",     "name": "Memorial Day",     "countryCode": "US",     "fixed": false,     "global": true,     "counties": null,     "launchYear": null,     "type": "Public"   },   {     "date": "2021-07-05",     "localName": "Independence Day",     "name": "Independence Day",     "countryCode": "US",     "fixed": false,     "global": true,     "counties": null,     "launchYear": null,     "type": "Public"   },   {     "date": "2021-09-06",     "localName": "Labor Day",     "name": "Labour Day",     "countryCode": "US",     "fixed": false,     "global": true,     "counties": null,     "launchYear": null,     "type": "Public"   },   {     "date": "2021-10-11",     "localName": "Columbus Day",     "name": "Columbus Day",     "countryCode": "US",     "fixed": false,     "global": false,     "counties": [       "US-AL",       "US-AZ",       "US-CO",       "US-CT",       "US-DC",       "US-GA",       "US-ID",       "US-IL",       "US-IN",       "US-IA",       "US-KS",       "US-KY",       "US-LA",       "US-ME",       "US-MD",       "US-MA",       "US-MS",       "US-MO",       "US-MT",       "US-NE",       "US-NH",       "US-NJ",       "US-NM",       "US-NY",       "US-NC",       "US-OH",       "US-OK",       "US-PA",       "US-RI",       "US-SC",       "US-TN",       "US-UT",       "US-VA",       "US-WV"     ],     "launchYear": null,     "type": "Public"   },   {     "date": "2021-11-11",     "localName": "Veterans Day",     "name": "Veterans Day",     "countryCode": "US",     "fixed": false,     "global": true,     "counties": null,     "launchYear": null,     "type": "Public"   },   {     "date": "2021-11-25",     "localName": "Thanksgiving Day",     "name": "Thanksgiving Day",     "countryCode": "US",     "fixed": false,     "global": true,     "counties": null,     "launchYear": 1863,     "type": "Public"   },   {     "date": "2021-12-24",     "localName": "Christmas Day",     "name": "Christmas Day",     "countryCode": "US",     "fixed": false,     "global": true,     "counties": null,     "launchYear": null,     "type": "Public"   } ]
--

**Comment by samtrion** [comment]
Thank you for the hint, we will look into this shortly.

**Comment by salmissira** [comment]
Thank you so much.
