### ISSUE TITLE
Netherlands: /Api/v2/PublicHolidays/{year}/{countryCode} returns wrong holiday type

### ISSUE THREAD

**Issue by cfleger** [nager/Nager.Date#279]
### Which country is affected?

NL

### The source of the information?

N/A

### Description

The type property does not comply with OpenAPI spec. 
Example:
`  {
    "date": "2022-04-15",
    "localName": "Goede Vrijdag",
    "name": "Good Friday",
    "countryCode": "NL",
    "fixed": false,
    "global": true,
    "counties": null,
    "launchYear": null,
    **"type": "School, Authorities"**
  }`

**Comment by tinohager** [comment]
@cfleger What exactly is wrong according to you?

https://github.com/nager/Nager.Date/blob/master/Src/Nager.Date/PublicHolidays/NetherlandsProvider.cs
https://www.rijksoverheid.nl/onderwerpen/arbeidsovereenkomst-en-cao/vraag-en-antwoord/goede-vrijdag-vrije-dag

**Comment by cfleger** [comment]
> @cfleger What exactly is wrong according to you?
> 
> https://github.com/nager/Nager.Date/blob/master/Src/Nager.Date/PublicHolidays/NetherlandsProvider.cs
> https://www.rijksoverheid.nl/onderwerpen/arbeidsovereenkomst-en-cao/vraag-en-antwoord/goede-vrijdag-vrije-dag
It is rendered as "School, Authorities". As per the swagger definition it is an enum, hence it could only be "School" or "Authorities". Or maybe it should be defined as an array of enums.

**Comment by samtrion** [comment]
Thank you, you have highlighted a problem with our API. Which we will try to fix with one of the next versions.

We understand that not every programming language supports flag enums.

**Comment by tinohager** [comment]
@cfleger Please check our new api endpoint v3

**Comment by cfleger** [comment]
Looks great. Thanks.
