### ISSUE TITLE
IsPublicHoliday returns true for LongWeekend date in Denmark.

### ISSUE THREAD

**Issue by qualityworld** [nager/Nager.Date#280]
**Which country is affected?**
Denmark - DK

**Description**
The 14th of May, in Denmark, is a friday where the banks are closed but it is NOT a public holiday, but part of the Nagger-type LongWeekends.
Looking at https://date.nager.at/PublicHoliday/Country/DK shows correctly that the 13th of May is a public holiday, but not the 14th, but .IsPublicHoliday still returns true for the 14th.
Is this a bug or can the type of wanted holiday-filter for 'true' be set somewhere ?  (ie. True only for Public, true for Bank, true for school...)

Thanks,
David

**Comment by samtrion** [comment]
Can you provide us with more official links for May 14, then we would include this in one of the next releases.

**Comment by tinohager** [comment]
No, I don't think it's a mistake here. Here simply a bridge day is used.

**Comment by samtrion** [comment]
But this bridge day is marked as bank, optional & school holiday. https://github.com/nager/Nager.Date/blob/07ec19378c6b7276af9fe5849acdf2ebcad97eb5/Src/Nager.Date/PublicHolidays/DenmarkProvider.cs#L38

**Comment by tinohager** [comment]
Okay this wrong, needBridgeDay is false

```
{
  "startDate":"2021-05-13",
  "endDate":"2021-05-16",
  "dayCount":4,
  "needBridgeDay":false
}
```

**Comment by qualityworld** [comment]
Hi again - i'm not sure i understand the talk about bridgeday etc., but i'm guessing it has to do with the friday being between the holiday (thursday) and the weekend.
It is correct that many companies close down friday, but it is not a public holiday. The website (https://date.nager.at/PublicHoliday/Country/DK) correctly says that only the 13th is public holiday and the 14th is bank closing day so it is just the true-response from '.IsPublicHoliday' that is wrong...
![image](https://user-images.githubusercontent.com/2625540/118359151-70eeb480-b582-11eb-9df4-c8c25ad214a6.png)
BUT i will have to verify next week if i'm using an older version from before two weeks ago, in case you fixed a bug there...

**Comment by tinohager** [comment]
@qualityworld The bridgeday is between a public holiday and the weekend. It is a working day but with this you have also a long weekend.
