### ISSUE TITLE
Missing public Holiday - Germany - Brandenburg

### ISSUE THREAD

**Issue by samtrion** [nager/Nager.Date#282]
**Which country is affected?**
DE

**Which public holiday is affected?**
Easter Sunday / Ostersonntag

**Which version of Nager.Date is used?**
All previous versions

**Additional context**
https://en.wikipedia.org/wiki/Public_holidays_in_Germany#List_by_state
In addition, the state of Brandenburg has formally declared Easter Sunday and Pentecost Sunday as public holidays. As these are Sundays anyway, they have been left away by the other states, nor counted in the table above (the state of Hesse even declared all Sundays public holidays).

**Comment by samtrion** [comment]
Officially, this also affects Hesse, but Hesse has declared every Sunday a holiday. Therefore, we should turn a blind eye here.

**Comment by Urtgard** [comment]
You used `_catholicProvider.EasterMonday` to add Easter Sunday.

**Comment by samtrion** [comment]
Thank you, that was really an unnecessary sloppiness mistake.
