### ISSUE TITLE
BUG switzerland Easter Monday same date as Whit Monday

### ISSUE THREAD

**Issue by stusas** [nager/Nager.Date#288]
### Which country is affected?

CH

### The source of the information?

found out when calling api

### Description
Easter Monday (localName Ostermontag) should be after the Good Friday. However, the name of Easter Monday is Whit Monday (wrong). I guess this is the reason why the date of Easter Monday is wrong (always same as Whit Monday)

![image](https://user-images.githubusercontent.com/24185321/118655209-992c1c80-b7e9-11eb-8710-96066f548f38.png)

btw, thanks for the API!!!

**Comment by tinohager** [comment]
wrong method `EasterMonday` -> https://github.com/nager/Nager.Date/blob/9685b2783f07451b1ed1830e7d850c79306709d8/Src/Nager.Date/PublicHolidays/SwitzerlandProvider.cs#L73

**Comment by tinohager** [comment]
@stusas Please check our new api endpoint v3

**Comment by tinohager** [comment]
we have push a new nuget package

**Comment by stusas** [comment]
@tinohager I get the correct data now, thanks a lot
