### ISSUE TITLE
Add Bosnia and Herzegovina holidays

### ISSUE THREAD

**Issue by sanitaf** [nager/Nager.Date#296]
### Which country is affected?

Bosnia and Herzegovina

### The source of the information?

https://en.wikipedia.org/wiki/Public_holidays_in_Bosnia_and_Herzegovina

### Description

Please, can you add Bosnia and Herzegovina public holidays?

**Comment by tinohager** [comment]
Thank you for your inquiry. Currently we are not adding any new countries. If you need it urgently we would be glad to receive a pull request for the desired country.

**Comment by djgamerr** [comment]
I have created a pull request for Bosnia and Herzegovina

**Comment by sanitaf** [comment]
@tinohager can you, please, review and approve pull request for Bosnia and Herzegovina?
Thank you.

**Comment by samtrion** [comment]
Here is still an open topic regarding regional holidays. Please see my review.
