### ISSUE TITLE
GetPublicHolidays method produces two instances of Good Friday holiday (same date) for US

### ISSUE THREAD

**Issue by jacksonisrael9** [nager/Nager.Date#304]
### Which country is affected?

US

### The source of the information?

[Link to the Information]

### Description

When the GetPublicHolidays method is called for CountryCode.US, the result has length 13, as Good Friday is repeated. The two Good Friday entries seem to be exactly identical. The error is observed in at least years 2020-2024 but probably affects all other years.

**Comment by samtrion** [comment]
Thank you for your message. This is correct behavior because unlike all other states in [Texas](https://github.com/nager/Nager.Date/blob/master/Src/Nager.Date/PublicHolidays/UnitedStatesProvider.cs#L50-L51), this holiday is only optional.
