### ISSUE TITLE
Battle of Arica is a specifi-Counties holiday

### ISSUE THREAD

**Issue by Marcelo366** [nager/Nager.Date#305]
### Which country is affected?

Chile

### The source of the information?

https://www.feriados.cl/

### Description

The Battle of Arica is a holiday in the Arica y Parinacota region

**Comment by tinohager** [comment]
https://github.com/nager/Nager.Date/blob/0992ffb26a4fa4d223be93222dc79c092ea1ad4b/Src/Nager.Date/PublicHolidays/ChileProvider.cs#L64

We have this holiday in the list?

**Comment by Marcelo366** [comment]
The holiday is in the list, but it shouldn't be a global holiday because is a specifi-counties holiday

![image](https://user-images.githubusercontent.com/44989613/126083442-f838f07c-341b-4cca-a3e3-cbb8585de34b.png)

**Comment by tinohager** [comment]
https://github.com/nager/Nager.Date/commit/f8f199fd22f428e39b41667b1e54a8528597b568
