### ISSUE TITLE
New to Js, getting cors error, can someone help me out :(

### ISSUE THREAD

**Issue by NiZZioN** [nager/Nager.Date#307]
Hello, I recently started doing JS and I know how to use the lang because I have some experience in java and c++ so programming isn't the issue, I was just trying to use the API and evertime I do without a proxy like corseverwhere I get a cors error, is there a way to fix it in native js? or is it not possible because I couldn't find a way to set the allow-cross-origin header in native js.

I know this is not really an issue, I am really sorry for that, I just have been stuck at this one point for 2 days now and whatever i try i don't succeed unless I use a proxy which I am trying to avoid because of the project I am working on.

Thanks in advance and have a good day!

![image](https://user-images.githubusercontent.com/64710666/125195133-a21ef480-e254-11eb-8aa9-72a6ed4155be.png)

**Comment by tinohager** [comment]
Hi, sorry but our api currently not open for CORS requests. But you can start your own container with active CORS support.
