### ISSUE TITLE
Start tagging releases (again)

### ISSUE THREAD

**Issue by CasperWSchmidt** [nager/Nager.Date#308]
### Description
This is more of a meta-issue. I was upgrading our dependencies from Nager.Date 1.27.x to the newest version, which broke our unit tests (because of #264). When trying to find out why the problem occured I tried up/downgrading the package until I was certain that 1.29.0 was the first version that broke our tests.

Now the issue: There are no tags for releases after 1.25.0. Could you please start tagging releases (again) to make it easier to find changes in a given release?

**Comment by tinohager** [comment]
for info we currently have the changelog
https://github.com/nager/Nager.Date/blob/master/CHANGELOG.md

**Comment by CasperWSchmidt** [comment]
Ah okay, 

> Fix DateSystem.IsPublicHoliday(DateTime date, CountryCode countryCode)

But it would still be nice to have the tags to easily find the actual code changes. The above description is not very informativ. "Fixing" some method incrementing the minor/feature version would not make me think that this was the cause of my issue :)

**Comment by billietlsfeir** [comment]
Hi,
what do you think if I opened a pull request that will set up [semantic release](https://github.com/semantic-release/semantic-release) in a github action for managing your releases automatically and an update on the action building docker images that will push images with tags corresponding to release tags ?

**Comment by tinohager** [comment]
New releases receive a tag again
