### ISSUE TITLE
Add method to check for other types of holidays (like IsPublicHoliday)

### ISSUE THREAD

**Issue by CasperWSchmidt** [nager/Nager.Date#309]
### Which country is affected?
ALL

### Description
In #264 `IsPublicHoliday` was changed to use a filter to only return true for holidays flagged with `Public`. In #146 I suggest renaming the public methods in DateSystem to remove "Public" from the name unless it really just operates based on holidays marked as `Public`. 

What I would like to have is a method `IsHoliday` that operates just like `IsPublicHoliday` with the addition of a parameter for types of holidays to consider (default could be `Public` to keep it consistent with how `IsPublicHoliday` works today).

**Comment by tinohager** [comment]
Hi looks this good for you?

https://github.com/nager/Nager.Date/blob/1ea439b30d30ad91a860f21a5d7761709cfa229b/src/Nager.Date/HolidaySystem.cs#L427-L447

**Comment by CasperWSchmidt** [comment]
Looks like what I was asking for 😊
