### ISSUE TITLE
Rename methods `GetPublicHolidays` to `GetHolidays`

### ISSUE THREAD

**Issue by CasperWSchmidt** [nager/Nager.Date#310]
### Which country is affected?
ALL

### Description
The public API in DateSystem.cs is filled with methods called `GetPublicHoliday(s)` even though they do not only return what is considered public holidays, but really returns ALL holidays (also those flagged as something else). IsPublicHoliday however now uses a filter so only holidays flagged as Public will yield true (since #264). This makes the API inconsistent.

Therefore I suggest renaming `GetPublicHolidays` to `GetHolidays` to make it clear that it returns ALL holidays. The method(s) could optionally take a parameter with types of holidays to return, but the filtering is also quite easy to do using LINQ after calling `GetHolidays`

**Comment by CasperWSchmidt** [comment]
This relates to the discussion in #146

**Comment by CasperWSchmidt** [comment]
@tinohager I'm a little confused. How is this completed? I'm no longer with the company I was when I was last active here, but I still very much enjoy the work you have done and believe it would be a shame to have an inconsistent API.

**Comment by tinohager** [comment]
The majority of users use the WebApi that is provided. We are causing a breaking change, the benefit of this is not big enough from one point of view. Also, no one has voted for a change.
