### ISSUE TITLE
DateSystem.IsPublicHoliday("8/30/2021", CountryCode.GB) is returning false when it should be true

### ISSUE THREAD

**Issue by DeLaphante** [nager/Nager.Date#311]
United Kingdom 

CountryCode.GB

### The source of the information?

![image](https://user-images.githubusercontent.com/6398105/126061529-ca0afe9b-c6be-4dc4-a08e-db20eebdd20f.png)

![image](https://user-images.githubusercontent.com/6398105/126061545-f88a63ee-fb3c-4063-96e6-ec7c4a4e5813.png)

### Description

The isPublicHoliday() method is returning false when it should be returning true because the 30th of August is a summer bank holiday for the United Kingdom

**Comment by tinohager** [comment]
It is not a public holiday for all counties.

https://github.com/nager/Nager.Date/blob/0992ffb26a4fa4d223be93222dc79c092ea1ad4b/Src/Nager.Date/PublicHolidays/UnitedKingdomProvider.cs#L68

**Comment by DeLaphante** [comment]
Right okay - my bad 😅
