### ISSUE TITLE
Good Friday is not a public holiday according to the NetherlandsProvider

### ISSUE THREAD

**Issue by dennisseders** [nager/Nager.Date#314]
### Which country is affected?

The Netherlands

https://www.government.nl/topics/working-hours/question-and-answer/public-holidays-in-the-netherlands

[Link to the Information]

### Description

According to the Dutch government Good Friday (locally named as Goede Vrijdag) is a public holiday in the Netherlands. This day is not an item in the PublicHoliday List of the the NetherlandsProvider class.

**Comment by tinohager** [comment]
It is not set to a public holiday. https://github.com/dennisseders/Nager.Date/blob/f2bb038f3dfef5e06535745879d458606a2a058c/Src/Nager.Date/PublicHolidays/NetherlandsProvider.cs#L43

the type is `PublicHolidayType.Authorities | PublicHolidayType.School`

**Comment by tinohager** [comment]
@dennisseders wikipedia has an other information to this holiday https://en.wikipedia.org/wiki/Public_holidays_in_the_Netherlands

**Comment by dennisseders** [comment]
@tinohager First: I believe that the official information (see the link which I shared). from our Dutch government should be considered as the source of truth and not Wikipedia.

When reading the Wikipedia article I can interpret this as that Good Friday is a national/public holiday. But **not all public holidays in the Netherlands are non-working days** for everyone and Good Friday is an example of that in the case of Authorities and Schools. 

Nager already consider Good Friday as a holiday for authorities and schools but it should also consider it as a public holiday.

I created pull request [#315](https://github.com/nager/Nager.Date/pull/315) to fix this issue.

Please not that I am from the Netherlands.
