### ISSUE TITLE
Switzerland: "Eidgenössischer Dank-, Buss- und Bettag" is not a public holiday

### ISSUE THREAD

**Issue by ivanstojkovicapps** [nager/Nager.Date#357]
Hi,

"Eidgenössischer Dank-, Buss- und Bettag" is not a public holiday in any of Switzerland cantons.
We checked with one client and got the information from CH districts.
We removed it for our import, but maybe you want to update your database.

**Comment by tinohager** [comment]
Hi to this topic we have some changes...

- https://github.com/nager/Nager.Date/issues/322
- https://github.com/nager/Nager.Date/pull/320
- https://github.com/nager/Nager.Date/pull/323

In this wikipedia articles it is a public holiday

https://en.wikipedia.org/wiki/Federal_Day_of_Thanksgiving,_Repentance_and_Prayer
> The Federal Day of Thanksgiving, Repentance and Prayer (German: Eidgenössischer Dank-, Buss- und Bettag, French: Jeûne fédéral, Italian: Digiuno federale) **is a public holiday in Switzerland.** It is an interfaith feast

https://de.wikipedia.org/wiki/Feiertage_in_der_Schweiz
> gesetzliche Feiertage, die aufgrund der Definition ihres Datums zwangsläufig auf einen Sonntag fallen, somit trivialerweise den Sonntagen gleichgestellt sind und deshalb im Folgenden nicht separat aufgeführt werden. Dies sind der Ostersonntag (gesamte Schweiz), der Pfingstsonntag (gesamte Schweiz) und der **Eidgenössische Dank-, Buss- und Bettag (gesamte Schweiz ausser Kanton Genf).**
