### ISSUE TITLE
Incorrect public Holiday - Bulgaria

### ISSUE THREAD

**Issue by iprodanovbg** [nager/Nager.Date#365]
**Which country is affected?**
Bulgaria

**Which public holiday is affected?**
1. Missing "**Orthodox Holy Saturday**" which is the day after "**Good Friday**" and on Cyrillic  is "Велика събота"
https://github.com/nager/Nager.Date/blob/0149eb5f72f8ee28c9976ecde35a92ae35551119/src/Nager.Date/PublicHolidays/BulgariaProvider.cs#L32-L34
2. "**National Awakening Day**" is not holiday and should be removed
https://github.com/nager/Nager.Date/blob/0149eb5f72f8ee28c9976ecde35a92ae35551119/src/Nager.Date/PublicHolidays/BulgariaProvider.cs#L40
3. "**St. Stephen's Day**" is incorrect and should be "**Christmas Holiday**" and on Cyrillic  is "Коледа"
https://github.com/nager/Nager.Date/blob/0149eb5f72f8ee28c9976ecde35a92ae35551119/src/Nager.Date/PublicHolidays/BulgariaProvider.cs#L43

**Which version of Nager.Date is used?**
1.31.0 and all previous versions

**Additional context**
Also if a holiday falls on a weekend, the following weekday will be a holiday.
Example: 2022 New Year's day is Saturday but next Monday (2022-01-03) will be day off.
This rule is applying to all non movable holidays.

The following page contains correct dates for each holiday in Bulgaria and can be used for reference - https://www.officeholidays.com/countries/bulgaria

https://www.parliament.bg/en/24 - Official page of the Bulgarian government for holidays in the country

**Comment by tinohager** [comment]
1. Orthodox Holy Saturday
I can not found any informations

2. National Awakening Day, it is removed also on wikipedia
https://en.wikipedia.org/w/index.php?title=Public_holidays_in_Bulgaria&type=revision&diff=894730629&oldid=885583905

3. "St. Stephen's Day" which translation is correct?
Wikipedia -> "Christmas Day"
parliament.bg -> "Christmas Day"
officeholidays.com -> "Christmas Holiday"

Is this translation wrong? "Рождество Христово"

**Comment by iprodanovbg** [comment]
> 1. Orthodox Holy Saturday
>        I can not found any informations
> 
>     2. National Awakening Day, it is removed also on wikipedia (👍🏻)
>        https://en.wikipedia.org/w/index.php?title=Public_holidays_in_Bulgaria&type=revision&diff=894730629&oldid=885583905
> 
>     3. "St. Stephen's Day" which translation is correct?
>        Wikipedia -> "Christmas Day"
>        parliament.bg -> "Christmas Day"
>        officeholidays.com -> "Christmas Holiday"
> 
> 
> Is this translation wrong? "Рождество Христово"

Hi Thino,

1. Orthodox Holy Saturday
   You can find more information about this holiday here: https://www.timeanddate.com/holidays/bulgaria/holy-saturday
   
3. "St. Stephen's Day" which translation is correct?
    We have two days of Christmas and "Christmas Day" is also correct for that date but the Cyrillic translate should be "Коледа"

**Comment by iprodanovbg** [comment]
Hi @tinohager it looks good to me except capital letter on the second word for line 33 and 35.
You can see from wikipedia they are written with lower letter for second word.
https://bg.wikipedia.org/wiki/%D0%A0%D0%B0%D0%B7%D0%BF%D0%B5%D1%82%D0%B8_%D0%BF%D0%B5%D1%82%D1%8A%D0%BA
https://bg.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%B8_%D0%BF%D0%BE%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D0%BD%D0%B8%D0%BA

**Comment by tinohager** [comment]
I have push a new nuget package

**Comment by iprodanovbg** [comment]
Thank you it looks good now.
