### ISSUE TITLE
Fix Bulgarian holidays' spelling

### ISSUE THREAD

**Issue by gkama** [nager/Nager.Date#369]
### Affected country

Bulgaria

### Affected public holiday

Good Friday, Easter Monday, Liberation Day, Unification Day, Saints Cyril and Methodius Day

### Source of the information

I am Bulgarian :)

### More information

The specified holidays have lowercase letters that are supposed to be uppercase letters and vice versa. This issue is to indicate their correct spelling.

- `"Разпети петък"` should be `"Разпети Петък"`
- `"Велики понеделник"` should be `"Велики Понеделник"`
- `"Ден на Освобождението на България от османско робство"` should be `"Ден на oсвобождението на България от Oсманско робство"`
- `"Ден на българската просвета и култура и на славянската писменост"` should be `"Ден на Българската просвета и култура и на славянската писменост"`
- `"Ден на Съединението"` should be `"Ден на cъединението"`

**Comment by tinohager** [comment]
@gkama Hi can you please check my changes https://github.com/nager/Nager.Date/commit/99e84ff06875f5c5f4b8839fbf4817b6d043151a

**Comment by gkama** [comment]
@tinohager Looks great. Thank you very much.

**Comment by tinohager** [comment]
@gkama is the new "HolySaturday" also good?

**Comment by gkama** [comment]
@tinohager actually, you can capitalize that one as well - `събота` is `Saturday` and all weekdays are capitalized. So, it'll become `Cъбота`

That's a good catch.

**Comment by gkama** [comment]
Actually, the comment seems to be correct and have the correct spelling - with lower case for weekdays. I did some more research on the Bulgarian google and that seems to be correct and I was incorrect. Thus, these are the correct spellings

```text
"Разпети петък"                vs. "Разпети Петък"
"Велики понеделник"            vs. "Велики Понеделник"
```

I apologize for the confusion.

**Comment by tinohager** [comment]
I have push a new nuget package

**Comment by gkama** [comment]
Thank you, looks great. I'm closing the issue now.
