### ISSUE TITLE
Fix Costa Rica - New public holiday

### ISSUE THREAD

**Issue by jzamora47** [nager/Nager.Date#370]
### Affected country

Costa Rica

### Affected public holiday

Día del Negro y la Cultura Afrocostarricense

### Source of the information

https://es.wikipedia.org/wiki/D%C3%ADa_Internacional_de_los_Afrodescendientes#:~:text=El%20D%C3%ADa%20Internacional%20de%20los,agosto%20desde%20el%20a%C3%B1o%202021.

### More information

Notes: Movable holiday: This year at least the holiday will be moved to Sunday, you can observe it in the following link:
[feriados_calendario_2022.pdf](https://www.mtss.go.cr/temas-laborales/feriados/feriados_calendario_2022.pdf)

**Comment by tinohager** [comment]
Is it a public holiday when everyone is off or a holiday when you have to work? Is it a recurring holiday? I have found information on the Internet that describes the holiday is always celebrated on the following Sunday?

https://www.officeholidays.com/countries/costa-rica/2023
