### ISSUE TITLE
Some Japanese Holidays missing about moving holiday

### ISSUE THREAD

**Issue by 75kSaNa** [nager/Nager.Date#371]
### Affected country

Japan

### Affected public holiday

"2022-02-11": "建国記念の日",     "2022-03-21": "春分の日",     "2022-07-18": "海の日",     "2022-08-11": "山の日",     "2022-09-19": "敬老の日",     "2022-09-23": "秋分の日",     "2022-10-10": "スポーツの日",     "2022-11-23": "勤労感謝の日",

### Source of the information

https://holidays-jp.github.io/

### More information

https://holidays-jp.github.io/api/v1/date.json get from Google Calender API.
also government of japan provide hholidays(https://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html#sports). But goverment's CSV data is not convinience.
Thank you your efforts. And appreciate this APIs.

**Comment by tinohager** [comment]
I have checked our source code for Japan, we have already tried to implement this but found no solution 
https://github.com/nager/Nager.Date/blob/master/src/Nager.Date/PublicHolidays/JapanProvider.cs

**Comment by 75kSaNa** [comment]
Thank you. I see your tried. 
This implementation appears to be solvable in JapanProvider.cs until 2299. There will be no other consequences. And if it can be supplied until 2299, it should be practically acceptable.
If it is possible I'll send GetVernalEquinox(int year) and GetAutumnalEquinox(int year) of code. Then I make pull request a few week later.
Thank you again your chekking and reply.

**Comment by 75kSaNa** [comment]
plograms Image like this
        //private DateTime GetVernalEquinox(int year)
        //{
        //    long curYear = 0, month = 0, day = 0, hour = 0, minutes = 0;
        //    double seconds = 0;
        //    var date = new AASDate();
        //    var spring = AASEquinoxesAndSolstices.NorthwardEquinox(year, true);
        //    date.Set(spring, true);
        //    date.Get(ref curYear, ref month, ref day, ref hour, ref minutes, ref seconds);
        //    var dt = new DateTime((int)curYear, (int)month, (int)day, (int)hour, (int)minutes, (int)seconds);
        //    var converDt = TimeZoneInfo.ConvertTimeFromUtc(dt, timeZone);
        //    return converDt;
        //}
        private DateTime GetVernalEquinox(int year)
        {
            long curYear = 0, month = 0, day = 0, hour = 0, minutes = 0;
            double seconds = 0;
            var date = new AASDate();
            var spring = AASEquinoxesAndSolstices.NorthwardEquinox(year, true);
            date.Set(spring, true);
            date.Get(ref curYear, ref month, ref day, ref hour, ref minutes, ref seconds);
            var mod = year % 4
            int array = new int[4];
            if (1900 < year && year < 1923){array={21,21,21,22};}
            if (1924 < year && year < 1959){array={21,21,21,21};}
            if (1960 < year && year < 1991){array={20,21,21,21};}
            if (1992 < year && year < 2023){array={20,20,21,21};}
            if (2024 < year && year < 2055){array={20,20,20,21};}
            if (2056 < year && year < 2091){array={20,20,20,20};}
            if (2092 < year && year < 2099){array={19,20,20,20};}
            if (2100 < year && year < 2123){array={20,21,21,21};}
            if (2124 < year && year < 2155){array={20,20,21,21};}
            if (2156 < year && year < 2187){array={20,20,20,21};}
            if (2188 < year && year < 2199){array={20,20,20,20};}
            if (2200 < year && year < 2223){array={21,21,21,21};}
            if (2224 < year && year < 2255){array={20,21,21,21};}
            if (2256 < year && year < 2287){array={20,20,21,21};}
            if (2288 < year && year < 2299){array={20,20,20,21};}
            var dt = new DateTime((int)curYear, (int)month, (int)array[mod], (int)hour, (int)minutes, (int)seconds);
            var converDt = TimeZoneInfo.ConvertTimeFromUtc(dt, timeZone);
            return converDt;
        }
        //private DateTime GetAutumnalEquinox(int year)
        //{
        //    long curYear = 0, month = 0, day = 0, hour = 0, minutes = 0;
        //    double seconds = 0;
        //    var date = new AASDate();
        //    var spring = AASEquinoxesAndSolstices.SouthwardEquinox(year, true);
        //    date.Set(spring, true);
        //    date.Get(ref curYear, ref month, ref day, ref hour, ref minutes, ref seconds);
        //    var dt = new DateTime((int)curYear, (int)month, (int)day, (int)hour, (int)minutes, (int)seconds);
        //    var converDt = TimeZoneInfo.ConvertTimeFromUtc(dt, timeZone);
        //    return converDt;
        //}
        
        private DateTime GetAutumnalEquinox(int year)
            long curYear = 0, month = 0, day = 0, hour = 0, minutes = 0;
            double seconds = 0;
            var date = new AASDate();
            var spring = AASEquinoxesAndSolstices.SouthwardEquinox(year, true);
            date.Set(spring, true);
            date.Get(ref curYear, ref month, ref day, ref hour, ref minutes, ref seconds);
            var mod = year % 4
            int array = new int[4];
            if (1900 < year && year < 1919){array={23,24,24,24};}
            if (1920 < year && year < 1947){array={23,23,24,24};}
            if (1948 < year && year < 1979){array={23,23,23,24};}
            if (1980 < year && year < 2011){array={23,23,23,23};}
            if (2012 < year && year < 2043){array={22,23,23,23};}
            if (2044 < year && year < 2075){array={22,22,23,23};}
            if (2076 < year && year < 2099){array={22,22,22,23};}
            if (2100 < year && year < 2107){array={23,23,23,24};}
            if (2108 < year && year < 2139){array={23,23,23,23};}
            if (2140 < year && year < 2167){array={22,23,23,23};}
            if (2168 < year && year < 2199){array={22,22,23,23};}
            if (2200 < year && year < 2227){array={23,23,23,24};}
            if (2228 < year && year < 2263){array={23,23,23,23};}
            if (2264 < year && year < 2291){array={22,23,23,23};}
            if (2292 < year && year < 2299){array={22,22,23,23};}
            var dt = new DateTime((int)curYear, (int)month, (int)array[mod], (int)hour, (int)minutes, (int)seconds);
            var converDt = TimeZoneInfo.ConvertTimeFromUtc(dt, timeZone);
            return converDt;
        }

**Comment by 75kSaNa** [comment]
Thanks reopen this issue. I tested Nager.Date.UnitTest and all passing.
But I can't make pullrequest. so sorry about.

changed
Nager.Date\src\Nager.Date\PublicHolidays\JapanProvider.cs line 143

        //private DateTime GetVernalEquinox(int year)
        //{
        //    long curYear = 0, month = 0, day = 0, hour = 0, minutes = 0;
        //    double seconds = 0;
        //    var date = new AASDate();
        //    var spring = AASEquinoxesAndSolstices.NorthwardEquinox(year, true);
        //    date.Set(spring, true);
        //    date.Get(ref curYear, ref month, ref day, ref hour, ref minutes, ref seconds);
        //    var dt = new DateTime((int)curYear, (int)month, (int)day, (int)hour, (int)minutes, (int)seconds);
        //    var converDt = TimeZoneInfo.ConvertTimeFromUtc(dt, timeZone);
        //    return converDt;
        //}

        private DateTime GetVernalEquinox(int year)
        {
            long curYear = year, month = 3, day = 21, hour = 0, minutes = 0;
            double seconds = 0;
            /*var date = new AASDate();
            var spring = AASEquinoxesAndSolstices.NorthwardEquinox(year, true);
            date.Set(spring, true);
            date.Get(ref curYear, ref month, ref day, ref hour, ref minutes, ref seconds);*/
            var mod = year % 4;
            var array = new int[4];
            if (1900 <= year && year <= 1923){array= new int[] {21,21,21,22};}
            if (1924 <= year && year <= 1959){array= new int[] {21,21,21,21};}
            if (1960 <= year && year <= 1991){array= new int[] {20,21,21,21};}
            if (1992 <= year && year <= 2023){array= new int[] {20,20,21,21};}
            if (2024 <= year && year <= 2055){array= new int[] {20,20,20,21};}
            if (2056 <= year && year <= 2091){array= new int[] {20,20,20,20};}
            if (2092 <= year && year <= 2099){array= new int[] {19,20,20,20};}
            if (2100 <= year && year <= 2123){array= new int[] {20,21,21,21};}
            if (2124 <= year && year <= 2155){array= new int[] {20,20,21,21};}
            if (2156 <= year && year <= 2187){array= new int[] {20,20,20,21};}
            if (2188 <= year && year <= 2199){array= new int[] {20,20,20,20};}
            if (2200 <= year && year <= 2223){array= new int[] {21,21,21,21};}
            if (2224 <= year && year <= 2255){array= new int[] {20,21,21,21};}
            if (2256 <= year && year <= 2287){array= new int[] {20,20,21,21};}
            if (2288 <= year && year <= 2299){array= new int[] {20,20,20,21};}
            var dt = new DateTime((int)curYear, (int)month, (int)array[mod], (int)hour, (int)minutes, (int)seconds);
            if(array.Length == 0){
                dt = new DateTime((int)curYear, (int)month, (int)day, (int)hour, (int)minutes, (int)seconds);
            }
            var timeZone = TimeZoneInfo.FindSystemTimeZoneById("Tokyo Standard Time");
            var converDt = TimeZoneInfo.ConvertTimeFromUtc(dt, timeZone);
            return converDt;
        }

        //private DateTime GetAutumnalEquinox(int year)
        //{
        //    long curYear = 0, month = 0, day = 0, hour = 0, minutes = 0;
        //    double seconds = 0;
        //    var date = new AASDate();
        //    var spring = AASEquinoxesAndSolstices.SouthwardEquinox(year, true);
        //    date.Set(spring, true);
        //    date.Get(ref curYear, ref month, ref day, ref hour, ref minutes, ref seconds);
        //    var dt = new DateTime((int)curYear, (int)month, (int)day, (int)hour, (int)minutes, (int)seconds);
        //    var converDt = TimeZoneInfo.ConvertTimeFromUtc(dt, timeZone);
        //    return converDt;
        //}
        
        private DateTime GetAutumnalEquinox(int year){
            long curYear = year, month = 9, day = 23, hour = 0, minutes = 0;
            double seconds = 0;
            /*var date = new AASDate();
            var spring = AASEquinoxesAndSolstices.SouthwardEquinox(year, true);
            date.Set(spring, true);
            date.Get(ref curYear, ref month, ref day, ref hour, ref minutes, ref seconds);*/
            var mod = year % 4;
            var array = new int[4];
            if (1900 <= year && year <= 1919){array = new int[] {23,24,24,24};}
            if (1920 <= year && year <= 1947){array = new int[] {23,23,24,24};}
            if (1948 <= year && year <= 1979){array = new int[] {23,23,23,24};}
            if (1980 <= year && year <= 2011){array = new int[] {23,23,23,23};}
            if (2012 <= year && year <= 2043){array = new int[] {22,23,23,23};}
            if (2044 <= year && year <= 2075){array = new int[] {22,22,23,23};}
            if (2076 <= year && year <= 2099){array = new int[] {22,22,22,23};}
            if (2100 <= year && year <= 2107){array = new int[] {23,23,23,24};}
            if (2108 <= year && year <= 2139){array = new int[] {23,23,23,23};}
            if (2140 <= year && year <= 2167){array = new int[] {22,23,23,23};}
            if (2168 <= year && year <= 2199){array = new int[] {22,22,23,23};}
            if (2200 <= year && year <= 2227){array = new int[] {23,23,23,24};}
            if (2228 <= year && year <= 2263){array = new int[] {23,23,23,23};}
            if (2264 <= year && year <= 2291){array = new int[] {22,23,23,23};}
            if (2292 <= year && year <= 2299){array = new int[] {22,22,23,23};}
            var dt = new DateTime((int)curYear, (int)month, (int)array[mod], (int)hour, (int)minutes, (int)seconds);
            if(array.Length == 0){
                dt = new DateTime((int)curYear, (int)month, (int)day, (int)hour, (int)minutes, (int)seconds);
            }
            var timeZone = TimeZoneInfo.FindSystemTimeZoneById("Tokyo Standard Time");
            var converDt = TimeZoneInfo.ConvertTimeFromUtc(dt, timeZone);
            return converDt;
        }

**Comment by tinohager** [comment]
I have push a new nuget package

**Comment by 75kSaNa** [comment]
I check on https://date.nager.at/swagger/index.html.  (api v2)
This result too helpful for me.
Arigato (^o^)
