### ISSUE TITLE
DateSystem.IsPublicHoliday not working?

### ISSUE THREAD

**Issue by ltickett** [nager/Nager.Date#377]
### NuGet Package Version

1.33.1

### More information

For some reason `DateSystem.IsPublicHoliday(new DateTime(2022, 8, 29), CountryCode.GB)` returns `false`.

Even though the API clearly shows 29/08/2022 as a public holiday?

I am using a workaround for now which works `DateSystem.GetPublicHolidays(date.Year, CountryCode.GB).Any(h => h.Date == date.Date);`

I'm sure it's user error, but not sure what i'm doing wrong? Thanks!

**Comment by tinohager** [comment]
This is not a public holiday is only available on some counties

Aug | 29.08.2022 | Summer Bank Holiday | Summer Bank Holiday |   | GB-ENG GB-WLS GB-NIR
-- | -- | -- | -- | -- | --

**Comment by ltickett** [comment]
Thanks for the speedy response @tinohager 

Nailed it: `DateSystem.IsPublicHoliday(date, CountryCode.GB, "GB-ENG");`

I think the API response threw me off as it does say `"types":["Public"]` but I guess this refers to something else?

**Comment by tinohager** [comment]
Can you explain your request better I can not follow you unfortunately.

**Comment by ltickett** [comment]
Sorry, I was saying:

`DateSystem.IsPublicHoliday(new DateTime(2022, 8, 29), CountryCode.GB)` did not work. But

`DateSystem.IsPublicHoliday(date, CountryCode.GB, "GB-ENG");` did work.

I am slightly confused what the types mean, but your answer helped me solve my problem- thank you.

**Comment by tinohager** [comment]
I am sorry that the countries define so inconsistent holidays. I would also much prefer to define it for a whole country without exceptions. 😄
