### ISSUE TITLE
Wrong names for public holidays in Greenland

### ISSUE THREAD

**Issue by mrApptastic** [nager/Nager.Date#381]
### Affected country

Greenland

### Affected public holidays

New Year's Day, Epiphany, Maundy Thursday, Vendredi saint (Good Friday), Easter Sunday, Lundi de Pâques (Easter Monday), Store Bededag (General Prayer Day), Ascension Day, Whit Monday, Christmas Eve, Christmas Eve, St. Stephen's Day, New Year's Eve.

### Source of the information

http://inatsisit.gl/Lov?rid=%7bFC643A98-2D13-4A94-86E5-48191F4C5748%7d&sc_lang=kl-GL

### More information

According to a list from Greenland's self-government many of the days in the list have wrong names (the linked document is both in Danish and Greenlandic - so you can compare with the Danish names - that's what I did). Currently, they are a mix of French and English.

<table border="1">
<tbody>
<tr><td>Danish</td><td>Kalaallisut (Greenlandic)</td><td>Week Day</td><td>Date</td><td>Day off</td></tr>
<tr><td>New Year's Day</td><td>Ukiortaaq</td><td>Saturday</td><td>01-jan</td><td>X</td></tr>
<tr><td>Epiphany</td><td>Kunngit pingasut ulluat</td><td>Thursday</td><td>06-jan</td><td></td></tr>
<tr><td>Maundy Thursday</td><td>Sisamanngortoq illernartoq</td><td>Thursday</td><td>14-apr</td><td>X</td></tr>
<tr><td>Good Friday</td><td>Tallimanngorneq tannaartoq</td><td>Friday</td><td>15-apr</td><td>X</td></tr>
<tr><td>Easter Sunday</td><td>Poorskip ullua</td><td>Sunday</td><td>17-apr</td><td>X</td></tr>
<tr><td>Easter Monday</td><td>Poorskip-aappaa</td><td>Monday</td><td>18-apr</td><td>X</td></tr>
<tr><td>General Prayer Day</td><td>Tussiarfik </td><td>Friday</td><td>13-maj</td><td>X</td></tr>
<tr><td>Ascension Day</td><td>Qilaliarfik</td><td>Thursday</td><td>26-maj</td><td>X</td></tr>
<tr><td>Bank Holiday</td><td>Atuanngiffik</td><td>Friday</td><td>27-maj</td><td></td></tr>
<tr><td>Pentecost</td><td>Piinsi</td><td>Sunday</td><td>05-jun</td><td>X</td></tr>
<tr><td>Whit Monday</td><td>Piinsip-aappaa</td><td>Monday</td><td>06-jun</td><td>X</td></tr>
<tr><td>Nationalday of Greenland</td><td>Kalaallit Nunaata inuiattut ullua (Ullortuneq)</td><td>Tuesday</td><td>21-jun</td><td>X</td></tr>
<tr><td>Christmas Eve</td><td>Juulliaraq</td><td>Saturday</td><td>24-dec</td><td></td></tr>
<tr><td>Christmas Day</td><td>Juullip ullua</td><td>Sunday</td><td>25-dec</td><td>X</td></tr>
<tr><td>St. Stephen's Day</td><td>Juullip-aappaa</td><td>Monday</td><td>26-dec</td><td>X</td></tr>
<tr><td>New Year's Eve</td><td>Ukiutoqaq</td><td>Saturday</td><td>31-dec</td></tr>
</tbody>
</table>

I will check up on the missing days (New Year's Eve and General Prayer's Day) and make a pull request.

**Comment by tinohager** [comment]
Thanks for the info the source we used had only English information.... https://en.wikipedia.org/wiki/Public_holidays_in_Greenland

**Comment by mrApptastic** [comment]
Just created a pull request to fix this (and updated the table above with English translations):
https://github.com/nager/Nager.Date/pull/384

**Comment by tinohager** [comment]
Thanks i have merge your pull request
