### ISSUE TITLE
Dockerfile / Web Project

### ISSUE THREAD

**Issue by Xyaren** [nager/Nager.Date#386]
### More information

Hello, I can see that the web project has been removed from the repository.
Where can I find that now ?
Where can I check the Dockerfile used to build the docker container ?

Best Regards,
Xyaren

**Comment by tinohager** [comment]
The Docker container is now only available for sponsors. If you need your own Docker container, you need to create your own Api project with your own Dockerfile .

**Comment by tinohager** [comment]
I have adjusted the sponsor packages, and now the access to the WebApi and Docker is included from the package "Commercial Basic". If the sponsoring is done via a company account, I still need the user who should get access.

**Comment by Xyaren** [comment]
I see, thank you for clarifying.

Does this also mean, that a license key for commercial use is starting from 20$ and more a month ?

One-Time Payments do not grant a license key ?

**Comment by tinohager** [comment]
The use of the public web api is free. Without a fee. You can also download the project and compile it yourself the use is also free.

Simply using the compiled library version on NuGet or the Docker container on Dockerhub requires a license key. They can get this from the smallest sponsor package.

If they want to have the extended access to the WebApi project with the updates to current .NET versions. And access to the Docker build scripts then this access is allowed from 20$ per month.
