### ISSUE TITLE
26-12 is not a National Holiday in PT

### ISSUE THREAD

**Issue by ajlf** [nager/Nager.Date#392]
### Affected country

Portugal

### Affected public holiday

26 December

### Source of the information

https://www.calendarr.com/portugal/feriados-2022/

### More information

26 December is not a holiday in Portugal

**Comment by tinohager** [comment]
The 26 December is only a public holiday in Madeira, is this not longer correct?

https://github.com/nager/Nager.Date/blob/master/src/Nager.Date/PublicHolidays/PortugalProvider.cs
`items.Add(new PublicHoliday(year, 12, 26, "Primeira Oitava", "St. Stephen's Day", countryCode, null, new string[] { "PT-30" }));`

**Comment by ajlf** [comment]
Sorry. It's 100% correct. I didn't notice that it was not a National Holiday.

**Comment by ajlf** [comment]
Sorry. It's 100% correct. I didn't notice that it was not a National Holiday.
