### ISSUE TITLE
New public holiday for New Zealand: Matariki

### ISSUE THREAD

**Issue by Kelerei** [nager/Nager.Date#393]
### Affected country

New Zealand

### Affected public holiday

Matariki

### Source of the information

https://www.mbie.govt.nz/business-and-employment/employment-and-skills/employment-legislation-reviews/matariki/matariki-public-holiday/

### More information

A new public holiday for New Zealand, called "Matariki", has recently been added.  The first instance of this occurring will be on 24th June 2022 (so, not much time to get this added).

The dates for the next 30 years, and the methology around how they were derived, can be found in [this PDF](https://www.mbie.govt.nz/assets/matariki-dates-2022-to-2052-matariki-advisory-group.pdf).

I can provide a PR with hardcoded dates for the next 30 years if need be, but converting the methodology into a working algorithm is sadly beyond me (I've tried modifying the algorithm used for calculating Easter, but several hours later my head is seriously spinning).

**Comment by tinohager** [comment]
https://github.com/nager/Nager.Date/pull/394

**Comment by Kelerei** [comment]
> #394

That PR looks good to me.
