### ISSUE TITLE
Spain - 25-Jul SANTIAGO APOSTOL not in Madrid county

### ISSUE THREAD

**Issue by florin-bujoreanu** [nager/Nager.Date#398]
### Affected country

Spain

### Affected public holiday

SANTIAGO APOSTOL

### Source of the information

https://www.comunidad.madrid/en/notas-prensa/2021/09/22/comunidad-madrid-aprueba-calendario-laboral-2022-12-dias-festivos-dos-locales-fijan-municipios

https://www.boe.es/diario_boe/txt.php?id=BOE-A-2021-17113

### More information

Approved in September 2021

**Comment by fidelpita** [comment]
@tinohager I have some proposed changes for the SpainProvider.cs file. What would be your preferred way to provide the changes?

**Comment by tinohager** [comment]
@fidelpita I don't know how familiar they are with github and git. Normally a pull request is the best solution for this.
