### ISSUE TITLE
Spain - Remove 19 March "San Jose" from Madrid

### ISSUE THREAD

**Issue by florin-bujoreanu** [nager/Nager.Date#400]
### Affected country

Spain

### Affected public holiday

San Jose

### Source of the information

https://www.boe.es/diario_boe/txt.php?id=BOE-A-2021-17113

 https://www.elmundo.es/como/2022/03/16/6231c1a6fdddff8e888b45c0.html   &     https://www.comunidad.madrid/en/notas-prensa/2021/09/22/comunidad-madrid-aprueba-calendario-laboral-2022-12-dias-festivos-dos-locales-fijan-municipios

### More information

This 2022, March 19 is a holiday only in the Valencian Community.

**Comment by tinohager** [comment]
Is there an official source for the adjustments, wikipedia, the government?

**Comment by florin-bujoreanu** [comment]
https://www.comunidad.madrid/ link attached contains a PDF with the latest approved holidays.
I could not find a wikipedia article on this regard.
The list has been confirmed by our organization users who reported the holidays for which I raised the issues.

**Comment by tinohager** [comment]
@florin-bujoreanu Can you check my pull request

**Comment by fidelpita** [comment]
In 2022, San José is a public holiday only in Comunitat Valenciana (ES-VC).
Source: https://www.boe.es/diario_boe/txt.php?id=BOE-A-2021-17113

**Comment by tinohager** [comment]
@fidelpita In my pull request i have two counties for 2022, is this information wrong?

```cs
 case 2022:
  counties = new string[] { "ES-GA", "ES-VC" };
```
https://github.com/nager/Nager.Date/pull/409/files

**Comment by fidelpita** [comment]
@tinohager For 2022, it is wrong, it should be only "ES-VC".
Unfortunately, until the official state gazette is published around October, we will not know for 2023.
