### ISSUE TITLE
Spain - To be added 6 June in Barcelona (CT)

### ISSUE THREAD

**Issue by florin-bujoreanu** [nager/Nager.Date#401]
### Affected country

Spain

### Affected public holiday

LUNES DE PASCUA GRANADA

### Source of the information

https://www.boe.es/diario_boe/txt.php?id=BOE-A-2021-17113
https://www.officeholidays.com/countries/spain/catalonia/2022

**Comment by florin-bujoreanu** [comment]
repeated from 2021, but is a local public holiday and can be changed next year

**Comment by tinohager** [comment]
@fidelpita this information valids?

Local Name: Lunes de pascua Granada
English: ?
One Time Holiday (for 2022)
Affected Countie: ES-CT

**Comment by fidelpita** [comment]
@tinohager 
Yes, it is correct. Perhaps, in the local name, with capital "P" in Pascua.
In English, it is Whit Monday. It is normally a local holiday in Barcelona only but in 2022 it is a regional holiday in Cataluña (ES-CT).

Source: https://www.barcelona.cat/culturapopular/en/noticia/infobarcelonaenwhat-do-we-celebrate-on-whit-monday_516072

**Comment by tinohager** [comment]
@fidelpita i have create a a PR, can you check it please

**Comment by fidelpita** [comment]
@tinohager It looks fine to me, thanks.
