### ISSUE TITLE
Spain - Remove April 14 from Barcelona

### ISSUE THREAD

**Issue by florin-bujoreanu** [nager/Nager.Date#402]
### Affected country

Spain

### Affected public holiday

Jueves Santo

### Source of the information
https://www.boe.es/diario_boe/txt.php?id=BOE-A-2021-17113
https://www.officeholidays.com/countries/spain/catalonia/2022

**Comment by tinohager** [comment]
Is there an official source for the adjustments, wikipedia, the government?

**Comment by florin-bujoreanu** [comment]
I could not find a wikipedia article on this regard.
The list has been confirmed by our organization users who reported the holidays for which I raised the issues.

**Comment by fidelpita** [comment]
There is no problem here. April 14th is correctly _not_ being presented by Nager.Date as a public holiday in Cataluña (ES-CT), the region to which Barcelona belongs.
