### ISSUE TITLE
Spain - To be added September 24 - La Mercé for Barcelona

### ISSUE THREAD

**Issue by florin-bujoreanu** [nager/Nager.Date#405]
### Affected country

Spain

### Affected public holiday

La Mercé

### Source of the information

https://www.boe.es/diario_boe/txt.php?id=BOE-A-2021-17113

### More information

To be added September 24 --- La Mercé for Barcelona

**Comment by fidelpita** [comment]
There is no problem here. September 24th (La Mercè) is a local holiday for **Barcelona city only**. It is _not_ a public holiday neither for Spain nor for Catalonia (the region to which Barcelona belongs).
