### ISSUE TITLE
Spain - To be added September 26 - Fiesta Local for Barcelona

### ISSUE THREAD

**Issue by florin-bujoreanu** [nager/Nager.Date#406]
### Affected country

Spain

### Affected public holiday

Fiesta Local

### Source of the information

https://www.boe.es/diario_boe/txt.php?id=BOE-A-2021-17113

### More information

To be added September 26 - Fiesta Local for Barcelona

**Comment by fidelpita** [comment]
There is no problem here. September 26th is a local holiday for Barcelona city only. It is not a public holiday neither for Spain nor for Catalonia (the region to which Barcelona belongs).
