### ISSUE TITLE
Spain - To be added May 16 - San Isidro for Madrid

### ISSUE THREAD

**Issue by florin-bujoreanu** [nager/Nager.Date#407]
### Affected country

Spain

### Affected public holiday

San Isidro

### Source of the information

https://www.madrid.es/portales/munimadrid/es/Inicio/Actividad-economica-y-hacienda/Empresa-y-comercio/Direcciones-y-telefonos/Calendario-oficial-laboral-y-de-dias-inhabiles-y-festivos-2022-para-Madrid/?vgnextfmt=default&vgnextoid=4e28f94b3c11c710VgnVCM1000001d4a900aRCRD&vgnextchannel=ed0c6d5ef88fe410VgnVCM1000000b205a0aRCRD

### More information

To be added May 16 - San Isidro for Madrid

**Comment by tinohager** [comment]
@florin-bujoreanu I can not found some infos for `San Isidro` in your source

**Comment by florin-bujoreanu** [comment]
The reason for this ticket is to add this holiday for Madrid. It is missing from the list in https://date.nager.at/PublicHoliday/Country/ES

**Comment by fidelpita** [comment]
date.nager does _not_ provide **local** holidays (only national and regional) and, as mentioned, this is a local holiday
