### ISSUE TITLE
Spain - To be added November 9 - Nuestra Señora de la Almudena for Madrid

### ISSUE THREAD

**Issue by florin-bujoreanu** [nager/Nager.Date#408]
### Affected country

Spain

### Affected public holiday

Nuestra Señora de la Almuden

### Source of the information

https://www.boe.es/diario_boe/txt.php?id=BOE-A-2021-17113

**Comment by tinohager** [comment]
Is this a new holiday that will be repeated from 2021 or a one-time holiday?

**Comment by florin-bujoreanu** [comment]
repeated from 2021, but is a local public holiday and can be changed next year

**Comment by florin-bujoreanu** [comment]
The reason for this ticket is to add this holiday for Madrid. It is missing from the list in https://date.nager.at/PublicHoliday/Country/ES

**Comment by fidelpita** [comment]
date.nager does _not_ provide **local** holidays (only national and regional) and, as mentioned, this is a local holiday
