### ISSUE TITLE
Sponsorship License Key

### ISSUE THREAD

**Issue by FixFlare** [nager/Nager.Date#429]
### NuGet Package Version

1.36.4

### More information

Is there a minimum donation amount to get a license key?

I donated but am not seeing the key appear as mentioned on this page: [https://github.com/sponsors/nager](https://github.com/sponsors/nager)

The wording at time of writing does not seem to imply a monthly donation or minimum amount is required.

If a minimum and/or monthly donation is required. Please update the text to indicate so.

Thanks,

**Comment by tinohager** [comment]
Sorry for the inconvenience the custom amount was recently automatically activated by GitHub for all projects and was not yet included.

**Comment by ciozmi** [comment]
I would like to receive a Licence Key to use as a Nuget Package in my project. 

Is this key available for One-Time sponsors as well?

**Comment by tinohager** [comment]
@ciozmi Yes, you will also receive a license key as a one-time sponsor, but if the key is changed in the future, you will not receive the new key.
