### ISSUE TITLE
The United States has created an "Indigenous People's Day" holiday.

### ISSUE THREAD

**Issue by FlaveC** [nager/Nager.Date#430]
### Affected country

United States

### Affected public holiday

Columbus Day/Indigenous People's Day

### Source of the information

https://www.usatoday.com/story/news/nation/2022/10/09/when-what-is-columbus-day-indigenous-peoples-day/8185066001/

### More information

I was wondering if you've thought about the Columbus Day/Indigenous People's Day holiday?

According to the above link:

"Over a dozen states and more than 130 local governments have chosen to not celebrate Columbus Day altogether or replace it with Indigenous Peoples Day. Many states celebrate both. Eleven U.S. states celebrate Indigenous Peoples Day or a holiday of a similar name via proclamation, while 10 others treat it as an official holiday. The 10 states that observe the holiday via proclamation are Arizona, California, Iowa, Louisiana, Michigan, Minnesota, Nevada, North Carolina, Virginia, Wisconsin, plus Washington, D.C.  And the 10 that officially celebrate it are Alabama, Alaska, Hawaii, Maine, Nebraska, New Mexico, Oklahoma, Oregon, South Dakota and Vermont."

Kinda messy but can we update the US holiday list?

**Comment by tinohager** [comment]
I think we have here a open pull request. I will look at this in detail over the next few days? Can you advise here 

https://github.com/nager/Nager.Date/pull/319

**Comment by FlaveC** [comment]
This rules for this holiday will be changing a lot over the coming years so I wonder is it wouldn't be easiest to just list both holidays for this date? List both "Columbus Day" and "Indigenous Peoples' Day" as holidays?

**Comment by tinohager** [comment]
I have included the information from this page, can you please check the changes in the pull request?
https://en.wikipedia.org/wiki/Indigenous_Peoples%27_Day_(United_States)#Indigenous_Peoples_Day_observers
