### ISSUE TITLE
Better replace Country with Region 

### ISSUE THREAD

**Issue by sasayaku** [nager/Nager.Date#431]
### More information

Such as Hong Kong,according to Wikipedia :Hong Kong (/ˈhɒŋkɒŋ/ (US) or /hɒŋˈkɒŋ/ (UK); Chinese: 香港, Cantonese: [hœ́ːŋ.kɔ̌ːŋ] (listen)), officially the Hong Kong Special Administrative Region of the People's Republic of China (abbr. Hong Kong SAR or HKSAR),[d] is a city and special administrative region of China on the eastern Pearl River Delta in South China. 

[https://en.wikipedia.org/wiki/Hong_Kong](https://en.wikipedia.org/wiki/Hong_Kong)

**Comment by tinohager** [comment]
If your problem involves the counties, then we only want to support that level, otherwise it becomes too cumbersome.

https://github.com/nager/Nager.Date/blob/9e37583e862296313646566b7595038b191c1147/src/Nager.Date/Model/PublicHoliday.cs#L38

**Comment by sasayaku** [comment]
I just want to say that Macao and Hong Kong are not  countries from a political and geographical point of view. And you classify they as 'countries'.

**Comment by tinohager** [comment]
Yes here you are right we refer to the https://en.wikipedia.org/wiki/ISO_3166-1 list

https://github.com/nager/Nager.Date/blob/9e37583e862296313646566b7595038b191c1147/src/Nager.Date/CountryCode.cs#L4
