### ISSUE TITLE
Numerous other date sites report more public holidays for Serbia RS

### ISSUE THREAD

**Issue by lightaffaire** [nager/Nager.Date#440]
### Affected country

Serbia

### Affected public holiday

3rd January 2023  New Year's Holiday

### Source of the information

https://www.officeholidays.com/calendars/planners/serbia/2023

### More information

https://www.officeholidays.com/calendars/planners/serbia/2023

https://www.timeanddate.de/kalender/?jahr=2023&land=38

Also:

2023-04-15 Orthadox Holy Saturday

**Comment by tinohager** [comment]
> https://en.wikipedia.org/wiki/Public_holidays_in_Serbia
If one of the non-religious holidays falls on a Sunday, then the next working day is a non-working day.

https://github.com/nager/Nager.Date/blob/main/src/Nager.Date/PublicHolidays/SerbiaProvider.cs

**Comment by lightaffaire** [comment]
Thanks for the fast reply. I looked at the wikipedia page and also noted the sentence "If one of the non-religious holidays falls on a Sunday, then the next working day is a non-working day." If that was the case then in 2028 the public holiday 2.1 (Jan) falls on a Sunday so Monday 3.1 would be a non-working day?  data returned for 2028 (or 2027 or 2029 just to be sure) does not reflect this... or did i totally misunderstand a public holiday that falls on a sunday ie. 2.1 will cause Monday 3.1 to be a vacation day?

**Comment by lightaffaire** [comment]
@tinohager have you had time to look at this issue? thank you

**Comment by tinohager** [comment]
We haven't really identified a set of rules here yet, have we?
