### ISSUE TITLE
Please consider adding available counties to /CountryInfo

### ISSUE THREAD

**Issue by Nevario** [nager/Nager.Date#441]
### Use case

Our software allows users to define their county, so that they are only shown holidays specific to them (in addition to the national holidays).

Rather than having to find another data source, it would be good if the county info was displayed on the `/api/v3/CountryInfo/AU` endpoint.

Currently it returns:

```
{
  "commonName": "Australia",
  "officialName": "Commonwealth of Australia",
  "countryCode": "AU",
  "region": "Oceania",
  "borders": []
}
```

but it would be great if it could return something like:

```
{
  "commonName": "Australia",
  "officialName": "Commonwealth of Australia",
  "countryCode": "AU",
  "region": "Oceania",
  "borders": [],
  "counties": ['AUS-NSW', AUS-QLD', 'AUS-VIC', '...']
}
```

**Comment by tinohager** [comment]
I have a second project if here all federal states would be supplemented we could do that. Nager.Date has not deposited the federal states for all countries.

https://github.com/nager/Nager.Country/blob/master/src/Nager.Country/CountryInfos/AustraliaCountryInfo.cs
