### ISSUE TITLE
Chile National plebiscite day appears as a recurring holiday instead of 2022 only

### ISSUE THREAD

**Issue by jeremielp** [nager/Nager.Date#442]
### Affected country

Chile

### Affected public holiday

National plebiscite day

### Source of the information

https://es.wikipedia.org/wiki/Plebiscito_constitucional_de_Chile_de_2022

### More information

The National plebiscite day was a banking holidays in Chile on 04 Sept, but **in 2022 ONLY**.
In the API, it appears also in 2023, as well as all the previous years. This is not correct.

**Comment by tinohager** [comment]
@jeremielp can you check my pull request?
