### ISSUE TITLE
South Africa - 27 December 2022

### ISSUE THREAD

**Issue by engelbrechtd** [nager/Nager.Date#446]
### Affected country

South Africa

### Affected public holiday

27 December: Public Holiday

### Source of the information

https://www.gov.za/about-sa/public-holidays

### More information

The South African president declared 27 December a public holiday in an announcement. This is not a fixed holiday.

https://www.gov.za/speeches/president-cyril-ramaphosa-declares-27-december-public-holiday-8-dec-2022-0000

**Comment by tinohager** [comment]
To me it looks like this holiday is a postponement for Christmas, when a holiday falls on a Sunday it is postponed to the next Monday, in this case the next Monday is also a holiday and then we have the postponement to Tuesday.

I think in this case we should implement a shift rule overall for South Africa.

**Comment by tinohager** [comment]
@engelbrechtd Hi can you check my pull request?
