### ISSUE TITLE
Duplicate holiday for GB

### ISSUE THREAD

**Issue by engelbrechtd** [nager/Nager.Date#447]
### Affected country

Great Britain

### Affected public holiday

New Year's Day

### Source of the information

https://date.nager.at/api/v3/PublicHolidays/2022/GB

### More information

Hi,

It seems there is a duplicate holiday for GB. 2022 it falls on the 3rd of January and for 2023 it falls on the 2nd. The holiday is exactly the same, except for the countries. The one entries countries are:  "counties": [ "GB-ENG", "GB-WLS"] and the other one is: "counties": ["GB-SCT"].

Should this not be a consolidated holiday, with 3 countries? something like: "counties": [ "GB-ENG", "GB-WLS", "GB-SCT"]

https://date.nager.at/api/v3/PublicHolidays/2023/GB

**Comment by tinohager** [comment]
It would be nicer if they were combined but the rules are already so complex here I don't want to make it even more complex. This is just a cosmetic error. https://github.com/nager/Nager.Date/blob/166e0b492e92e9c8b0b95bb887d1e430e720d742/src/Nager.Date/PublicHolidays/UnitedKingdomProvider.cs#L48
