### ISSUE TITLE
New annual public holiday (from 2023 onwards) for the Republic of Ireland

### ISSUE THREAD

**Issue by thatcow** [nager/Nager.Date#448]
### Affected country

Republic of Ireland

### Affected public holiday

Saint Brigid's Day (Imbolc)

### Source of the information

https://en.wikipedia.org/wiki/Public_holidays_in_the_Republic_of_Ireland

### More information

From 2023 to be observed on 1 February if it is a Friday, or on the first Monday of February otherwise. Corresponds with the traditional festival of [Imbolc](https://en.wikipedia.org/wiki/Imbolc).

**Comment by tinohager** [comment]
@thatcow can you check my pull request please
