### ISSUE TITLE
Incorrect Holidays for Saskatchewan, Canada

### ISSUE THREAD

**Issue by hugh35** [nager/Nager.Date#452]
### Affected country

Canada

### Affected public holiday

Civic Holiday and Boxing Day

### Source of the information

https://www.saskatchewan.ca/business/employment-standards/public-statutory-holidays/list-of-saskatchewan-public-holidays

### More information

Saskatchewan has a civic holiday on the first weekend of August.  It's called Saskatchewan Day but is the same as other August civic holidays.  The link provided has a list of provincial holidays.

The API lists Boxing day as St. Stephan's day.  It's mostly referred to as Boxing Day:

https://www.bankofcanada.ca/press/upcoming-events/bank-of-canada-holiday-schedule/

**Comment by tinohager** [comment]
Can you check the Pull Request please
