### ISSUE TITLE
ENHANCEMENT: Information on counties by country

### ISSUE THREAD

**Issue by abydox88** [nager/Nager.Date#461]
### More information

It would be very interesting if the CountryInfo endpoint would additionally return all the counties of the country with their name and code. 

This request comes as a result of the fact that the Endpoint PublicHolidays already returns all counties with a holiday, but there is no way to know the name of the county, only its code.

Thank you very much for the hard work.

**Comment by tinohager** [comment]
We currently do not have the information recorded for all countries. But you could, of course, start including that data in this project. https://github.com/nager/Nager.Country

https://github.com/nager/Nager.Date/issues/441
