### ISSUE TITLE
New plugin available for OutSystems.com

### ISSUE THREAD

**Issue by ajlf** [nager/Nager.Date#465]
### More information

There is a proposed solution of the Nager API in OutSystems

https://www.outsystems.com/forge/component-overview/13208/nager-country-holidays-api

**Comment by tinohager** [comment]
What is the question?

**Comment by ajlf** [comment]
Hi. It is more a comment (information) than a question. Possible not in the best place. Sorry :(

**Comment by tinohager** [comment]
Is the nuget package used here or the public web api?

**Comment by ajlf** [comment]
Public web api.

**Comment by tinohager** [comment]
Do you plan to publish the plugin on Github as well?

**Comment by tinohager** [comment]
Here we would also need a plugin as far as I know the existing ones are outdated.... https://marketplace.uipath.com/listings?query=holiday
