### ISSUE TITLE
Missing Brazil carnival -  20.02.2023

### ISSUE THREAD

**Issue by bednarczyk9** [nager/Nager.Date#466]
### Affected country

Brazil

### Affected public holiday

Carnival

### Source of the information

https://www.cgisaopaulo.gov.in/list-of-holidays-2023.php

### More information

Brazil has Carnival  on 20 February which is a recurring holiday.
https://www.qppstudio.net/publicholidays2023/brazil.htm

**Comment by tinohager** [comment]
Source Code
https://github.com/nager/Nager.Date/blob/main/src/Nager.Date/PublicHolidays/BrazilProvider.cs

**Comment by tinohager** [comment]
Is there a page on the official homepage with an overview of the last years?
https://www.gov.br

**Comment by bednarczyk9** [comment]
Unfortunately, I don't know.

**Comment by tinohager** [comment]
Are they from Brazil? Has the 2nd day of Carnival always been a holiday or has something changed here in recent years?

**Comment by bednarczyk9** [comment]
I don't know. I will to write to somebody from Brazil about it..

pt., 17 lut 2023, 09:39 użytkownik Tino Hager ***@***.***>
napisał:

**Comment by bednarczyk9** [comment]
> Are they from Brazil? Has the 2nd day of Carnival always been a holiday or has something changed here in recent years?

I've received the following answer: In Brazil, every day of Carnival is a public holiday, except during the pandemic period when the Carnival holiday was cancelled.

See below for a website that lists the holidays in our state.

https://www.feriados.com.br/feriados-sao_paulo-sp.php

**Comment by jhonnymoreira** [comment]
Carnival is an optional holiday.

**Comment by tinohager** [comment]
@jhonnymoreira @bednarczyk9 @diegobrum

Is there an expert among you who can tell me what we set correctly?

**Comment by jhonnymoreira** [comment]
@tinohager, gimme a day. I'll do some research on that topic and get back to you.

**Comment by bednarczyk9** [comment]
My answer comes from someone who lives in Brazil. Banks are closed on these days.

**Comment by Orsatti** [comment]
Neither the 20th nor the 21th of february are hollidays in Brazil.  https://www.in.gov.br/web/dou/-/portaria-me-n-11.090-de-27-de-dezembro-de-2022-454503426

**Comment by jhonnymoreira** [comment]
@Orsatti, thank you! This is what I was trying to find.

🇧🇷
II - 20 de fevereiro, Carnaval (ponto facultativo);
III - 21 de fevereiro, Carnaval (ponto facultativo);
IV - 22 de fevereiro, quarta-feira de cinzas (ponto facultativo até às 14 horas);

🇺🇸
II - February 20, Carnaval (optional holiday)
III - February 21, Carnaval (optional holiday)
IV - February 22, Ash Wednesday (optional holiday until 2pm)

**Comment by tinohager** [comment]
@Orsatti In your link of the National Press from brazil (https://www.in.gov.br/web/dou/-/portaria-me-n-11.090-de-27-de-dezembro-de-2022-454503426)

Translated to uk english
II - February 20, Carnival (non-business day);
III - February 21, Carnival (non-business day);

Translated to us english
II - February 20, Carnival (optional);
III - February 21, Carnival (optional);

Unfortunately, the result is completely different. Since we have received the information from @bednarczyk9 that there is no work, I would take over for 20 February.

**Comment by bednarczyk9** [comment]
Hi, According my colleague from Brazil, banks don't work those days (20, 21.03.2023). It seems that companies decide if their workers have holiday or not.

According Geppetto :)
"Ponto facultativo" is a term used in Brazil to indicate a discretionary or optional holiday, also known as a "bridging holiday". It means that the day is not a mandatory holiday, but employers may choose to give their employees the day off or require them to work.

In practice, "Ponto facultativo" is often declared for days that fall between a mandatory holiday and a weekend, creating an extended weekend for workers. However, this can vary depending on the institution or company, and it's always a good idea to check with your employer or the relevant government agency to confirm whether a particular day is a holiday or not.

**Comment by tinohager** [comment]
Then we define the holidays like this **PublicHolidayType.Bank | PublicHolidayType.Optional**

```
new PublicHoliday(easterSunday.AddDays(-47), "Carnaval", "Carnival", countryCode, null, null, PublicHolidayType.Bank | PublicHolidayType.Optional);
new PublicHoliday(easterSunday.AddDays(-48), "Carnaval", "Carnival", countryCode, null, null, PublicHolidayType.Bank | PublicHolidayType.Optional);
```
