### ISSUE TITLE
Danish government just abolished Great Prayer Day

### ISSUE THREAD

**Issue by jemunk** [nager/Nager.Date#469]
### Affected country

Denmark

### Affected public holiday

Great Prayer Day

### Source of the information

https://www.dw.com/en/denmark-abolishes-public-holiday-to-boost-defense-spending/a-64846302

### More information

2023 is the last year having Great Prayer Day in Denmark.

**Comment by tinohager** [comment]
@jemunk Hi, i have add the new logic can you check it please?

**Comment by jemunk** [comment]
Your code says up to and including 2024. But Great Prayer Day is only up to 2023, meaning 2023 is the last year having Great Prayer Day.

**Comment by tinohager** [comment]
@jemunk That's right I fixed it

**Comment by jemunk** [comment]
Thanks. Great work you did with this library!
