### ISSUE TITLE
Germany - International Women's Day missing for county Mecklenburg-Vorpommern

### ISSUE THREAD

**Issue by leeh1234** [nager/Nager.Date#470]
### Affected country

Germany

### Affected public holiday

International Women's Day March 8th

### Source of the information

https://de.wikipedia.org/wiki/Internationaler_Frauentag#Der_Frauentag_als_gesetzlicher_Feiertag

### More information

International Women's Day is also a public holiday in Mecklenburg-Vorpommern starting from 2023

**Comment by tinohager** [comment]
Additional source: https://www.ndr.de/nachrichten/mecklenburg-vorpommern/Frauentag-in-MV-Landtag-beschliesst-neuen-Feiertag,frauentag370.html

**Comment by tinohager** [comment]
@leeh1234 Hi, can you check the pull requests, thanks
