### ISSUE TITLE
Australia - Queen's birthday renamed to King's Birthday

### ISSUE THREAD

**Issue by goldfish1974** [nager/Nager.Date#477]
### Affected country

Australia (Probably NZ and any other Commonwealth country too...maybe Canada, etc. etc)

### Affected public holiday

Queen's birthday

### Source of the information

https://en.wikipedia.org/wiki/Public_holidays_in_Australia

### More information

Following the death of HRH Queen Elizabeth II, the Name of the holiday will be known as King's birthday. It is also possible that the date changes for each state of Australia.

You will need to create a split for prior to Jan 2023 and post Jan 2023 to have Queen's Birthday prior to and King's birthday following 2023.

**Comment by tinohager** [comment]
Thank you for the information, I will incorporate it as soon as possible.

**Comment by tinohager** [comment]
Hi can you check my pull request?

**Comment by goldfish1974** [comment]
Hi,

New Zealand also renamed their holiday from Queen's to King's birthday. This was raised in my original issue notes.

Official page here: https://www.govt.nz/browse/work/public-holidays-and-work/public-holidays-and-anniversary-dates/

It is also a shifting date, but it looks like NewZealandProvider.cs already has that date sorted, just not the rename from Queen's to King's like the change to AustraliaProvider.cs does in your pull request.

Doing an almost identical fix for NewZealandProvider.cs (except for the correct date that it already has (and differs from) Australia).

N.B. As originally raised, Canada doesn't suffer from this issue as they call their day "Victoria Day", so nothing to do there with this issue.

Other than that, your pull request looks good!

**Comment by tinohager** [comment]
For traceability, it is quite handy to make multiple issues and pull requests. I have had it in the past that I wanted to know why I changed something so I will duplicate the issue for the other countries.

**Comment by goldfish1974** [comment]
Thate makes sense, especially for something like Nager.Date

**Comment by tinohager** [comment]
Thanks
