### ISSUE TITLE
Germany - Missing Holiday for DE-BY : Maria Himmelfahrt

### ISSUE THREAD

**Issue by FabianSer** [nager/Nager.Date#479]
### Affected country

Germany

### Affected public holiday

Mariä Himmelfahrt

### Source of the information

https://de.wikipedia.org/wiki/Mari%C3%A4_Aufnahme_in_den_Himmel

**Comment by tinohager** [comment]
I think your Information is not correct.

In Bavaria, only in the current approx. 1700 municipalities with a predominantly Catholic population; in the remaining approx. 350 Bavarian municipalities, not a public holiday.

> ***In Bayern nur in den derzeit ca. 1700 Gemeinden mit überwiegend katholischer Bevölkerung, in den restlichen ca. 350 bayerischen Gemeinden kein gesetzlicher Feiertag.
Source: https://www.dgb.de/gesetzliche-feiertage-deutschland
