### ISSUE TITLE
Bulgaria - Missing weekend shift

### ISSUE THREAD

**Issue by Caragop-Ioan-Alexandru** [nager/Nager.Date#481]
### Affected country

Bulgaria

### Affected public holiday

New Year's Day, Saint George's Day, Christmas Holiday

### Source of the information

https://www.qppstudio.net/publicholidays2023/bulgaria.htm

### More information

- New Year's Day 2nd January 2023
- May 8th - Saint George's Day
- 27th December - Christmas Holiday

The Wikipedia (https://en.wikipedia.org/wiki/Public_holidays_in_Bulgaria) page is not updated with those mentioned days above because they are somehow compensatory for the others which are in the weekend. (they have a compensatory law for this)

https://xn--b1aekbb1acci5f.net/ <- this is a Bulgarian website which gives additional information.

！ 2 януари e допълнителен почивен ден, понеже 1 януари се пада в неделя.
！ 8 май e допълнителен почивен ден, понеже 6 май се пада в събота.
！ 27 декември е допълнителен почивен ден, понеже 24 декември се падат в неделя.
The above description means: ！ January 2nd is an additional day off because January 1st falls on a Sunday.

**Comment by tinohager** [comment]
I have added the weekend move logic can you please check it out

**Comment by Caragop-Ioan-Alexandru** [comment]
Hey,

Thank you so much. I'll check it out and let you know Tomorrow.

Have a good day,
Alex

**Comment by tinohager** [comment]
The changes currently in the pull request here

https://github.com/nager/Nager.Date/pull/486/files

**Comment by tinohager** [comment]
Thanks
