### ISSUE TITLE
Chile - New Year's Day

### ISSUE THREAD

**Issue by natenho** [nager/Nager.Date#483]
### Affected country

Chile

### Affected public holiday

New Year's Day

### Source of the information

https://www.feriados.cl/

### More information

Apparently there are 2 public New Year's holidays in Chile and some other countries

**Comment by tinohager** [comment]
If the holiday falls on a Sunday, it will be postponed to the following Monday. (Observed)

https://github.com/nager/Nager.Date/blob/c179463066b5c985598a0ee4b2c0951e67f88493/src/Nager.Date/PublicHolidays/ChileProvider.cs#L57
