### ISSUE TITLE
Mexico - New Year's Day

### ISSUE THREAD

**Issue by natenho** [nager/Nager.Date#484]
### Affected country

Mexico

### Affected public holiday

New Year's Day

### Source of the information

https://elpais.com/mexico/2022-12-25/calendario-2023-asi-quedan-los-puentes-dias-festivos-y-vacaciones-escolares-en-mexico.html

### More information

Apparently, in Mexico, 02/01 is not always a public holiday when 01/01 is on a weekend

**Comment by tinohager** [comment]
I find it very interesting that Wikipedia says something different.
https://en.wikipedia.org/wiki/Public_holidays_in_Mexico

**Comment by tinohager** [comment]
I cannot find any reasonable sources. Can you provide reliable information here?

**Comment by tinohager** [comment]
@natenho Can you help?

**Comment by natenho** [comment]
@tinohager sorry, I missed this message. I would not be able to help anyway (I'm not a native), but I've found some misleading information around so I considered to open this issue in case someone could refute with reliable sources.

**Comment by tinohager** [comment]
OK, unfortunately I'm not a local either, so I guess there's nothing left to do at the moment but wait for someone to get back to me with the right information.
