### ISSUE TITLE
Australia - WA state missing Easter Sunday holiday

### ISSUE THREAD

**Issue by mattwalshdev** [nager/Nager.Date#488]
### Affected country

Australia - AU-WA - Western Australia

### Affected public holiday

Easter Sunday

### Source of the information

https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia

### More information

Hi there, could you please add the AU-WA state to list of states that have Easter Sunday as a public holiday. An excerpt from the official gov page I linked (Easter Sunday was established as a public holiday in Western Australia in February 2022.)

Thanks for your work on this API.
Matt

**Comment by tinohager** [comment]
Thanks
