### ISSUE TITLE
Liechtenstein - Fix holiday only for Banking

### ISSUE THREAD

**Issue by tpcgold** [nager/Nager.Date#491]
### More information

In Switzerland and Liechtenstein, we have some Holidays only valid for Banks. 
See e.g.:
https://www.llb.li/de/kontakt/bankfeiertage

Please add a new field so we know if it is a Public or Bank Holiday

**Comment by tinohager** [comment]
This logic is available, see here
https://github.com/nager/Nager.Date/blob/main/src/Nager.Date/Model/PublicHolidayType.cs

**Comment by tpcgold** [comment]
in this case a lot of the "Holidays" for Liechtenstein are wrong flagged as Public
Source:
https://www.llb.li/de/kontakt/bankfeiertage

(all with the asterisk are Bank Holidays)

**Comment by tinohager** [comment]
I'll have to look through and adjust that at my leisure, I'll do it in the next few days....

**Comment by tinohager** [comment]
Can you check the output is now good?

> 01.01.2023 New Year's Day (Neujahr)  Public
02.01.2023 St. Berchtold's Day (Berchtoldstag)  Bank
06.01.2023 Epiphany (Heilige Drei Könige)  Public
02.02.2023 Candlemas (Mariä Lichtmess)  Public
19.03.2023 Saint Joseph's Day (Josefstag)  Public
07.04.2023 Good Friday (Karfreitag)  Bank
10.04.2023 Easter Monday (Ostermontag)  Public
01.05.2023 Labour Day (Tag der Arbeit)  Public
18.05.2023 Ascension Day (Auffahrt)  Public
28.05.2023 Pentecost (Pfingstsonntag)  Public
29.05.2023 Whit Monday (Pfingstmontag)  Public
08.06.2023 Corpus Christi (Fronleichnam)  Public
15.08.2023 National Holiday (Staatsfeiertag)  Public
08.09.2023 Nativity of Our Lady (Maria Geburt)  Public
01.11.2023 All Saints Day (Allerheiligen)  Public
08.12.2023 Immaculate Conception (Mariä Empfängnis)  Public
24.12.2023 Christmas Eve (Heiliger Abend)  Bank
25.12.2023 Christmas Day (Weihnachten)  Public
26.12.2023 St. Stephen's Day (Stephanstag)  Public
31.12.2023 New Year's Eve (Silvester)  Bank

**Comment by tinohager** [comment]
Holidays are now online https://date.nager.at/PublicHoliday/Country/LI
