### ISSUE TITLE
Germany - Missing Gründonnerstag (School holiday)

### ISSUE THREAD

**Issue by ViktorDimitrievski** [nager/Nager.Date#495]
### Affected country

Germany

### Affected public holiday

Gründonnerstag & Augsburger Friedensfest

### Source of the information

https://www.feiertage-deutschland.de/2023/

### More information

**Date: 06.04.2022**
**Name:  Gründonnerstag**
**CountryCode: DE-BW**
Baden-Württemberg
(1) Schüler haben an den Feiertagen Gründonnerstag und Reformationsfest schulfrei (siehe Feiertagsgesetz §4 Abs. 3).

**Date: 08.08.2022** 
**Name: Augsburger Friedensfest** 
**CountryCode: DE-BY**
Description: 
Bayern
(3) Das Augsburger Friedensfest ist nur in der Stadt Augsburg ein gesetzlicher Feiertag (siehe Bayerisches Feiertagsgesetz Art. 1 Abs. 2).

**Comment by tinohager** [comment]
Hi

Holidays that are valid only for one city are not included, they must refer to a state.

**Comment by ViktorDimitrievski** [comment]
Hello @tinohager ,

In this case, what can be the solution for the Nager to have these holidays as well with some additional flag that will mark these holidays as non-state holidays ?

**Comment by tinohager** [comment]
@ViktorDimitrievski 

Holidays that refer to a city we do not include it is now already very time-consuming to maintain everything. That would go beyond the scope. If they need them they have to maintain them themselves.

**Comment by ViktorDimitrievski** [comment]
Okay understood, and yeah would be too much to handle per city for every country. In that case, we can close this issue. Thank you very much!
I appreciate your effort and work to build this library!
