### ISSUE TITLE
France - Counties are not available anymore

### ISSUE THREAD

**Issue by Heimlich757** [nager/Nager.Date#496]
### Endpoint

v3/PublicHolidays/2023/FR

### More information

Unfortunately, the counties for France are no longer available.

**Comment by tinohager** [comment]
We only support states/counties for country provider, the old entries have not the state of a county more a region

<https://github.com/nager/Nager.Date/commit/dd1b4cc293f5e4f006335cffff654c8474d08eba>
[dd1b4cc293f5e4f006335cffff654c8474d08eba.png]
Optimize france provider, add counties · ***@***.***<https://github.com/nager/Nager.Date/commit/dd1b4cc293f5e4f006335cffff654c8474d08eba>
github.com<https://github.com/nager/Nager.Date/commit/dd1b4cc293f5e4f006335cffff654c8474d08eba>

**Comment by Heimlich757** [comment]
Ok, thank you very much for clarification. Is there any change to get public holidays for the regions as well?

**Comment by tinohager** [comment]
No sorry this project support holiday too state level.
