### ISSUE TITLE
Netherlands: Whit Monday is called Tweede Pinksterdag

### ISSUE THREAD

**Issue by marcelerkel** [nager/Nager.Date#497]
### Affected country

Netherlands

### Affected public holiday

WhitMonday

### Source of the information

https://en.wikipedia.org/wiki/Public_holidays_in_the_Netherlands 

### More information

Whit Monday is called 'Tweede Pinksterdag' (in line with Tweede Paasdag and Tweede Kerstdag). 

From the wikipedia source:

| Date | English name | Dutch name | Notes |
|--------|--------------------|------------------|---------------------------------------------------------------|
| 7 weeks after Easter | [Pentecost](https://en.wikipedia.org/wiki/Pentecost) |	Pinksteren |A two-day holiday (Sunday and the subsequent Monday), called Eerste Pinkstersdag and Tweede Pinksterdag (lit. First Pentecost Day and Second Pentecost Day) |

**Comment by tinohager** [comment]
The bug is the local name of `Whit Monday`?
It is not `Pinksteren` it is `Tweede Pinksterdag`

**Comment by tinohager** [comment]
@marcelerkel Can you check the pull request? Thanks :)

**Comment by marcelerkel** [comment]
Looks good to me.

**Comment by tinohager** [comment]
A new release is available
