### ISSUE TITLE
Incorrect public holiday returned for Thüringen, Germany in 2018

### ISSUE THREAD

**Issue by georgfranz** [nager/Nager.Date#500]
### Endpoint

api/v3/publicholidays/2018/DE

### More information

I have encountered an issue with the public holidays API at https://date.nager.at/api/v3/publicholidays/2018/DE. The API returns the "Weltkindertag" (World Children's Day) as a public holiday for Thüringen, Germany in 2018. However, this holiday was introduced in Thüringen in 2019, not 2018. The dataset correctly states the introduction year, but the API still returns this holiday for 2018.

Code to reproduce:

$client = new \GuzzleHttp\Client();
$response = $client->request('GET', "https://date.nager.at/api/v3/publicholidays/2018/DE");
Expected behavior:
The API should not list "Weltkindertag" as a public holiday for Thüringen, Germany in 2018, as it was introduced in 2019.

Actual behavior:
The API returns "Weltkindertag" as a public holiday for Thüringen, Germany in 2018, even though it was introduced in 2019.

Possible solution:
Check the year in the date for each holiday and compare it to the introduction year before returning the list of holidays for a specific year and region.

Thank you for looking into this issue.

**Comment by tinohager** [comment]
A new release is available
