### ISSUE TITLE
June 13th is missing as a regional public holiday in Lisbon

### ISSUE THREAD

**Issue by tiagojadduarte** [nager/Nager.Date#506]
### Affected country

Portugal

### Affected public holiday

Dia de Santo António

### Source of the information

https://www.lisbon.net/holidays

### More information

The API is not returning the June 13th as a municipal holiday in Lisbon (Portugal) while it is.

https://pt.wikipedia.org/wiki/13_de_junho#Feriados_e_eventos_c%C3%ADclicos

**Comment by tinohager** [comment]
Holidays are provided only up to the state level. City holidays are not supported.
