### ISSUE TITLE
New Zealand - Queen's birthday renamed to King's Birthday

### ISSUE THREAD

**Issue by goldfish1974** [nager/Nager.Date#511]
### Affected country

New Zealand

### Affected public holiday

Queen's birthday -> King's Birthday

### Source of the information

https://www.govt.nz/browse/work/public-holidays-and-work/public-holidays-and-anniversary-dates/

### More information

Affected country
New Zealand

Affected public holiday
Queen's birthday

Source of the information
https://www.govt.nz/browse/work/public-holidays-and-work/public-holidays-and-anniversary-dates/

More information
Following the death of HRH Queen Elizabeth II, the Name of the holiday will be known as King's birthday.

You will need to create a split for prior to Jan 2023 and post Jan 2023 to have Queen's Birthday prior to and King's birthday following 2023.

Same solution as for Australia in issue #477

**Comment by tinohager** [comment]
A new release is available
