### ISSUE TITLE
Belgium: Missing Bank Holidays

### ISSUE THREAD

**Issue by cdeseck** [nager/Nager.Date#513]
### More information

In Belgium, there are 3 bank holiday next to the national holidays.

They are:
- Good Friday: the Friday before Easter Monday (e.g. 07-04-2023)
- The day after Ascension Day (e.g. 19-05-2023)
- Boxing Day: 26th of December (e.g. 26-12-2023)

Would it be possible to implement this logic?

You can check with the following link (all dates with * are bank holidays):
https://www.bnpparibasfortis.be/public/nl/public/particulieren/sluitingsdagen

**Comment by tinohager** [comment]
second source for bank: https://www.nbb.be/en/about-national-bank/national-bank-belgium/public-holidays
currently we are use only this source: https://en.wikipedia.org/wiki/Public_holidays_in_Belgium

> Would it be possible to implement this logic?
yes it is

**Comment by tinohager** [comment]
A new release is available

**Comment by cdeseck** [comment]
Thanks a lot for implementing this.

Just one more question:
If I use the API method "IsTodayPublicHoliday" on a Bank Holiday, would it return a 200 (Today is a public holiday) or a 204 (Today is not a public holiday)?
I work for a bank and I was hoping to use the API to know when the bank is closed (Public or Bank Holiday).
