### ISSUE TITLE
API Method with date input

### ISSUE THREAD

**Issue by cdeseck** [nager/Nager.Date#518]
### More information

Would it be possible to have an API method in which you manually input the date (year-month-day) and country code and have it return if that specific day is a holiday or not?
It might offer a bit more flexibility than the IsTodayPublicHoliday method and it would allow not having to set the offset parameter. Cause this can change for some countries.

**Comment by tinohager** [comment]
What would they need this function for? Basically I do not want to increase the traffic additionally to the api that all days are retrieved individually. But if there is a sensible reason for it we can of course talk about it.
