### ISSUE TITLE
Argentina - Mon 10/09/2023 moved

### ISSUE THREAD

**Issue by paa-listas** [nager/Nager.Date#525]
### Affected country

Argentina

### Affected public holiday

Day of Respect for Cultural Diversity

### Source of the information

https://www.argentina.gob.ar/interior/feriados-nacionales-2023

### More information

One holiday have been moved, and another added for tourist concerns. 

NEW      -->  13. "Feriado con fines turísticos"

MOVED --> 16. "Día del Respeto a la Diversidad Cultural (12/10)" Ex dia de la raza.

**Comment by tinohager** [comment]
If a holiday is added for tourism purposes is it considered a Public Holiday?

**Comment by tinohager** [comment]
No answer

**Comment by paa-listas** [comment]
Sorry for the delay!. Yes is considered as a Public Holiday.
