### ISSUE TITLE
Slovenia - New holiday

### ISSUE THREAD

**Issue by alenjursic1997** [nager/Nager.Date#526]
### Affected country

Slovenia

### Affected public holiday

Solidarity day

### Source of the information

https://www.gov.si/teme/drzavni-prazniki-in-dela-prosti-dnevi/

### More information

Slovenia has new public holiday named Solidarity day. It's work free.
This holiday is on 14th August launching with year 2023.

This code needs to be added in _SloveniaProvider.cs_ file
`items.Add(new PublicHoliday(year, 8, 14, "dan solidarnosti", "Solidarity day", countryCode, 2023));`

**Comment by tinohager** [comment]
If I understand it correctly, this is a one-time holiday for the year 2023 to help the flood victims. Did I understand that correctly?
Source: https://www.gov.si/novice/2023-08-10-14-avgust-dan-solidarnosti/

**Comment by alenjursic1997** [comment]
Yes, this is only one-time holiday. Do you have a solution for one-time holidays?

**Comment by tinohager** [comment]
Yes, we have had that in other countries as well

https://github.com/nager/Nager.Date/blob/b65aac18413c4c9deef93a90893fdfdbd5ced2d6/src/Nager.Date/PublicHolidays/GermanyProvider.cs#L164-L172

https://github.com/nager/Nager.Date/blob/b65aac18413c4c9deef93a90893fdfdbd5ced2d6/src/Nager.Date/PublicHolidays/GermanyProvider.cs#L74
