### ISSUE TITLE
Where do I source my licence key?

### ISSUE THREAD

**Issue by simonziegler** [nager/Nager.Date#528]
### More information

Hi, many thanks for an excellent library!

I just upgraded my sponsorship to Corporate Basic and wonder where to get my licence key.

Also do I add this to the start of `Program.cs`?

```
DateSystem.LicenseKey = "My key value";
```

Thanks,    Simon

**Comment by tinohager** [comment]
Hi Simon

The LicenseKey is in the welcome message of the sponsor ship. Did you find it?

**Comment by simonziegler** [comment]
I did, and got it working. Thank you!
