### ISSUE TITLE
On the Canary Islands there are some local holidays that are missing

### ISSUE THREAD

**Issue by wolfgangihloff** [nager/Nager.Date#538]
### Affected country

Spain

### Affected public holiday

Nuestra Señora del Pino

### Source of the information

http://www.gobiernodecanarias.org/boc/2023/072/007.html

### More information

There are some labor free holidays on each island that seem to be missing in the Spanish calendar. Should I contribute these or are they too local and would overwhelm the system? It seems for Canarias alone in Spain would need to be added:
• In El Hierro: September 25, feast of Our Lady of the Kings.
• In Fuerteventura: on September 15, feast of Our Lady of the Rock.
• In Gran Canaria: on September 8, feast of Our Lady of the Pine.
• In La Gomera: October 9, feast of Our Lady of Guadalupe.
• In Lanzarote and La Graciosa: on September 15, feast of Our Lady of the Volcanoes.

However there as these are only on  specific islands, it would be wrong to indicate them being applicable for all of ES-CN, are there other examples where a third further geopgrahic detail is added or best then to go with
Details added to the description only?:
* ES-CN
* Our Lady of the Pine (Gran Canaria only)

**Comment by tinohager** [comment]
Hi, Nager.Date supports only state level holidays a deeper level of detail overwhelms the effort of maintenance

**Comment by wolfgangihloff** [comment]
@tinohager that would be a great disclaimer? I must admit as German, I was unaware of such municapality level holidays, that seems not something common in Germany. Is this a common thing in many countries to have more local holidays? Afterall these holidays are not just optional celebrations but government offices and schools and most companies close?

**Comment by tinohager** [comment]
Since I am Austrian, I did not know that at the beginning of this project. Unfortunately, there are far too many special rules for the holidays
