### ISSUE TITLE
Canada - Missing public holiday for British Columbia

### ISSUE THREAD

**Issue by yuqian5** [nager/Nager.Date#539]
### Affected country

Canada

### Affected public holiday

British Columbia Day

### Source of the information

https://www2.gov.bc.ca/gov/content/employment-business/employment-standards-advice/employment-standards/statutory-holidays

### More information

BC day is the first Monday of every August. Please add to the database, thank you.

**Comment by tinohager** [comment]
Can it be that we have only a name problem here, wikipedia does not list everyone individually here in their table
https://en.wikipedia.org/wiki/Public_holidays_in_Canada

https://github.com/nager/Nager.Date/blob/8cf99edc1bc06ccda91ea23920391cb61037c94d/src/Nager.Date/PublicHolidays/CanadaProvider.cs#L74

**Comment by yuqian5** [comment]
Seems like it. I took the liberty to create a pull request. #551

**Comment by tinohager** [comment]
new version is puplished
