### ISSUE TITLE
IsTodayPublicHoliday for federal states

### ISSUE THREAD

**Issue by apkicz** [nager/Nager.Date#541]
### Endpoint

/api/v3/IsTodayPublicHoliday

### More information

Hi,

It looks it is not possible check public holiday for concrete federal state. And as the response does not contains any body, it is not possible to check it from the response.
E.g., it is not possible to verify there is a public holiday for DE-BW.

BR,

Pavel @ apki.cz (sponsor)

**Comment by tinohager** [comment]
Hi, is your hardware limited that you use this endpoint originally this is intended for IOT devices and otherwise we recommend to pick up the holidays for a country and then evaluate the list yourself.

**Comment by tinohager** [comment]
I tried to explain it with this info "This is a special endpoint for curl".

At the moment, the end point is not designed for the federal state level. We can create an issue and see if anyone else needs.
