### ISSUE TITLE
Getting list federal states for supported countries

### ISSUE THREAD

**Issue by apkicz** [nager/Nager.Date#542]
### Endpoint

/api/v3/CountryInfo

### More information

Hi,

Would it be possible to return list of federal states ISO-3166-2 codes for ContryInfo endpoint?
(For us, it is much more useful information than borders).

BR,

Pavel @ apki.cz (sponsor)

**Comment by tinohager** [comment]
Hi, we do not have ISO-3166-2 countries for all countries. They are only included for certain countries.
If they are interested in countries information we would have still additionally Nager.Country in the offer. https://github.com/nager/Nager.Country

**Comment by apkicz** [comment]
Hi,

Thanks, we checked the .zip packege for Nager.Country, but there is no information about federal states (tried for DE). Any plans to add it?

BR,

Pavel

**Comment by tinohager** [comment]
Sorry federal states is not a part of the Nager.Country project.  Maybe this page will help you https://geopostcodes.com
