### ISSUE TITLE
Australia - New Year's Day weekend shift

### ISSUE THREAD

**Issue by Motifier** [nager/Nager.Date#543]
### Affected country

Australia

### Affected public holiday

New Year's Day

### Source of the information

https://www.australia.gov.au/public-holidays

### More information

New Year's Day weekend should show as Jan 2nd when the actual date is a weekend 

https://www.australia.gov.au/public-holidays or your competitor https://holidayapi.com/countries/au/2023

![image](https://github.com/nager/Nager.Date/assets/11881520/babe504f-aecf-400f-a492-f48bf7a8317e)

**Comment by tinohager** [comment]
Thanks for the info, the issue has been fixed
