### ISSUE TITLE
Kosovo country in source code is remarked by mistake

### ISSUE THREAD

**Issue by atias007** [nager/Nager.Date#544]
### NuGet Package Version

1.45.00

### More information

in CountryCode.cs
Kosovo country in source code is remarked by mistake
![image](https://github.com/nager/Nager.Date/assets/56188592/15f367d2-ce66-4b67-a53d-c52e4a6f678b)

**Comment by tinohager** [comment]
Sorry it is not a mistake, it is not official assigned

https://github.com/nager/Nager.Country/issues/14
https://github.com/nager/Nager.Date/issues/139
