### ISSUE TITLE
Serbia - Weekendshift non-religious holidays

### ISSUE THREAD

**Issue by djordjedjukic** [nager/Nager.Date#545]
### Affected country

Serbia

### Affected public holiday

New Year's Day

### Source of the information

https://en.wikipedia.org/wiki/Public_holidays_in_Serbia

### More information

 If one of the non-religious holidays falls on a Sunday, then the next working day is a non-working day.
 
 ie. In 2023, New Year's Days were 1, 2, and 3. January because of 1.1.2023. was Sunday.

**Comment by tinohager** [comment]
Thanks for the info, the issue has been fixed

**Comment by djordjedjukic** [comment]
Hey, I really appreciate the swift reaction from your side.
