### ISSUE TITLE
Japan - Health and Sports Day has been renamed Sports Day

### ISSUE THREAD

**Issue by fetus-hina** [nager/Nager.Date#547]
### Affected country

Japan

### Affected public holiday

Health and Sports Day

### Source of the information

- Wikipedia (EN): https://en.wikipedia.org/wiki/Sports_Day_(Japan)
- Government Page (JA): https://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html

### More information

In Japan, 体育の日 ("Health and Sports Day") was changed to スポーツの日 ("Sports Day") due to a revision of the law governing national holidays.
This change is effective from 2020.

Organizing for this Holiday:
<table>
<tr><th>Year</th><th>Date</th><th>Name (EN)</th><th>Name (JA)</th></tr>
<tr><td>- 1965</td><td></td><td>(Not a holiday)</td><td></td></tr>
<tr><td>1966 - 1999</td><td>Oct 10</td><td>Health and Sports Day</td><td>体育の日</td></tr>
<tr><td>2000 - 2019</td><td>2nd Mon in Oct</td><td>Health and Sports Day</td><td>体育の日</td></tr>
<tr><td>2020 *</td><td>Jul 24</td><td>Sports Day</td><td>スポーツの日</td></tr>
<tr><td>2021 *</td><td>Jul 23</td><td>Sports Day</td><td>スポーツの日</td></tr>
<tr><td>2022 - </td><td>2nd Mon in Oct</td><td>Sports Day</td><td>スポーツの日</td></tr>
</table>
* This holiday was moved for 2020 and 2021 due to the Tokyo Olympics.

**Comment by tinohager** [comment]
thank you for the detailed explanation

**Comment by tinohager** [comment]
The issue has been fixed

**Comment by fetus-hina** [comment]
:+1:
