### ISSUE TITLE
Australia - ACT - Reconciliation Day - Missing

### ISSUE THREAD

**Issue by Motifier** [nager/Nager.Date#553]
### Affected country

Australia

### Affected public holiday

Reconciliation Day

### Source of the information

https://www.australia.gov.au/public-holidays

### More information

[https://www.cmtedd.act.gov.au/open_government/inform/act_government_media_releases/rachel-stephen-smith-mla-media-releases/2017/reconciliation-day-public-holiday-an-australian-first
Observed on the First Monday after](https://www.cmtedd.act.gov.au/open_government/inform/act_government_media_releases/rachel-stephen-smith-mla-media-releases/2017/reconciliation-day-public-holiday-an-australian-first)
"Reconciliation Day will be held each year on the first Monday on or after the 1967 Referendum anniversary date of 27 May – the start of National Reconciliation Week."

**Comment by tinohager** [comment]
https://github.com/nager/Nager.Date/blob/98a936379e968b62fe1c43864f8da0f0a2521885/src/Nager.Date/PublicHolidays/AustraliaProvider.cs#L74

I think this holiday is not missing?
