### ISSUE TITLE
Australia QLD - Royal Queensland Show (Brisbane area only) / EKKA People's Day

### ISSUE THREAD

**Issue by Motifier** [nager/Nager.Date#554]
### Affected country

Australia

### Affected public holiday

Royal Queensland Show

### Source of the information

https://www.qld.gov.au/recreation/travel/holidays/public

### More information

Although this is listed as Brisbane only, it is one of the primary public holidays listed on the main gov website. Regional Holidays are typically listed separately.

The Royal National Agricultural (RNA) Show Day (Brisbane only) is held on the Wednesday during the RNA Show period. The RNA Show commences on the first Friday in August, unless the first Friday is prior to 5 August, then it commences on the second Friday of August.

Here's the current days Holiday API shows it being for comparison:
 https://holidayapi.com/holidays/au/royal-national-agricultural-show-day

**Comment by tinohager** [comment]
This holiday is only valid for a city.

> B City of Brisbane only. The Royal National Agricultural (RNA) Show Day (Brisbane only) is held on the Wednesday during the RNA Show period.

https://en.wikipedia.org/wiki/Public_holidays_in_Australia


Sorry but city holiday are not supported: https://github.com/nager/Nager.Date#data-precision
