### ISSUE TITLE
Brazil - Black Consciousness Day

### ISSUE THREAD

**Issue by btduarte** [nager/Nager.Date#557]
### Affected country

Brazil

### Affected public holiday

Black Consciousness Day

### Source of the information

https://nationaltoday.com/black-consciousness-day/

### More information

Over the years, more and more cities have declared this day as a holiday, especially large cities like São Paulo and Rio de Janeiro, perhaps it would be interesting to add this holiday, even if it was with the name of the cities highlighted. I've been working on process automation and I'm using your API as a data source to capture holidays, so here's a suggestion: this holiday is held on 20/11, in the cities mentioned they are holidays, in the rest optional, the way you consider, it is already valid. Thanks for listening

**Comment by tinohager** [comment]
Thanks for the information, I have decided on the level of detail of the federal lands for the project. Otherwise it will be too costly for me.

**Comment by btduarte** [comment]
oh ok, what exactly does that mean? Do you intend to implement?

**Comment by tinohager** [comment]
| Type |      Supported      |
|----------|:-------------:|
| Country Public Holiday |  Yes |
| Subdivisions Holiday (ISO 3166-2) |   Yes   |
| City Holiday | No |

**Comment by btduarte** [comment]
Oh thank you, I didn't understand before! Good week
