### ISSUE TITLE
South Africa - Public Holiday 15 December

### ISSUE THREAD

**Issue by KeeganFargher** [nager/Nager.Date#559]
### Affected country

South Africa

### Affected public holiday

Springboks victory

### Source of the information

https://www.youtube.com/live/h9ajJCXLaLw?si=Ccfz5vtklQ06sQUI&t=1780

### More information

This is a one time holiday for winning the rugby world cup :) 15 December 2023.

**Comment by tinohager** [comment]
- https://www.citizen.co.za/news/ramaphosa-declares-15-december-a-public-holiday/
- https://fakazanews.com/2023/10/30/president-cyril-declares-december-15-public-holiday-to-celebrate-springboks-victory/
- https://www.timeslive.co.za/politics/2023-10-30-watch-live-sa-finds-out-if-there-will-be-a-public-holiday-after-boks-world-cup-triumph/

**Comment by tinohager** [comment]
Hi, can you check my pull request?

**Comment by KeeganFargher** [comment]
Looks great 😊
