### ISSUE TITLE
USA: Day After Thanksgiving

### ISSUE THREAD

**Issue by bmakan** [nager/Nager.Date#563]
### Affected country

USA

### Affected public holiday

The Day After Thanksgiving

### Source of the information

https://www.timeanddate.com/holidays/us/day-after-thanksgiving

### More information

I am not from the USA, so I don't know the exact rules on this, but I found multiple sources claiming this is celebrated as a public holiday in 22 states. In 20 of them, it's called "Day After Thanksgiving", in Louisiana it's "Acadian Day" and in Nevada it's a "Family Day".

Colleagues from California confirmed they don't work on this day.

**Comment by tinohager** [comment]
So according to my research, it's not really a public holiday that it's up to the companies whether they release it or not.

- https://en.wikipedia.org/wiki/Public_holidays_in_the_United_States
- https://en.wikipedia.org/wiki/Federal_holidays_in_the_United_States

**Comment by bmakan** [comment]
The situation looks to be quite messy in the US. I got a list of holidays our company supports and half the federal holidays are not on the list, but there are a few extra ones.
As far as I'm concerned, you can close the issue without adding this holiday. That would be the consistent thing as well.
