### ISSUE TITLE
Australia - WA - King's Birthday missing

### ISSUE THREAD

**Issue by mleech** [nager/Nager.Date#564]
### Affected country

Australia - WA

### Affected public holiday

King's Birthday

### Source of the information

https://en.wikipedia.org/wiki/Public_holidays_in_Australia

### More information

See also: https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia

From https://en.wikipedia.org/wiki/King%27s_Official_Birthday : "As Western Australia celebrates [Western Australia Day](https://en.wikipedia.org/wiki/Western_Australia_Day) (formerly known as Foundation Day) on the first Monday in June, the [governor of Western Australia](https://en.wikipedia.org/wiki/Governor_of_Western_Australia) each year proclaims the day on which the state will observe the King's Birthday, based on school terms and the [Perth Royal Show](https://en.wikipedia.org/wiki/Perth_Royal_Show).[[1]](https://en.wikipedia.org/wiki/King%27s_Official_Birthday#cite_note-1) There is no firm rule to determine this date, though it is usually the last Monday of September or the first Monday of October."

**Comment by tinohager** [comment]
@mleech Are you interested in maintaining the annual announcements here? Otherwise, the date will not be right for the next few years.
