### ISSUE TITLE
I cannot use Nager.date("Referenced assembly does not have a strong name" error)

### ISSUE THREAD

**Issue by hisashi-kuwahara** [nager/Nager.Date#569]
### More information

![スクリーンショット 2023-12-10 111409](https://github.com/nager/Nager.Date/assets/143512194/dcef7ba0-588e-4bc3-9f78-3c50951a51e3)
Could you please sign the assembly and rebuild it?

**Comment by tinohager** [comment]
In my view, there is no good reason why we should introduce this. Have you thought about using the online api?

> Strong naming has no benefits on .NET Core/5+
https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming
