### ISSUE TITLE
Bulgaria's liberation day is on Sunday, March 3, 2024

### ISSUE THREAD

**Issue by FGremlin** [nager/Nager.Date#585]
### Affected country

Bulgaria

### Affected public holiday

Liberation Day

### Source of the information

https://speech-repository.webcloud.ec.europa.eu/news/national-day-bulgaria

### More information

**Comment by tinohager** [comment]
This is the weekend shift logic for the holiday.

<https://github.com/nager/Nager.Date/issues/481>
Bulgaria - Missing weekend shift · Issue #481 · nager/Nager.Date<https://github.com/nager/Nager.Date/issues/481>
github.com<https://github.com/nager/Nager.Date/issues/481>
[apple-touch-icon-180x180-a80b8e11abe2.png]<https://github.com/nager/Nager.Date/issues/481>

**Comment by FGremlin** [comment]
Is it possible to get them without shift?

**Comment by tinohager** [comment]
there is currently no such option

**Comment by tinohager** [comment]
The new version now has the option available but currently only in the nuget package
