### ISSUE TITLE
Types specified in response only has public in the list

### ISSUE THREAD

**Issue by Nayeem1996** [nager/Nager.Date#599]
### Endpoint

https://date.nager.at/api/v3/publicholidays/2024/de

### More information

Currently trying to find all bank holidays for different countries, namely German. The response form the call should return this:

//publicHoliday.Date -> The date
    //publicHoliday.LocalName -> The local name
    //publicHoliday.Name -> The english name
    //publicHoliday.Fixed -> Is this public holiday every year on the same date
    //publicHoliday.Global -> Is this public holiday in every county (federal state)
    //publicHoliday.Counties -> Is the public holiday only valid for a special county ISO-3166-2 - Federal states
    //publicHoliday.Type -> Public, Bank, School, Authorities, Optional, Observance

The publicholiday.Type returned only contains 'Public' and nothing else. Could you look into this please?

Thanks in advance, other than this issue, it's a great project :).

**Comment by tinohager** [comment]
Then they are not entered for Germany. There are many countries where this information is not available.

For Liechtenstein, for example, it is stored
https://date.nager.at/PublicHoliday/Liechtenstein

If you need it for Germany, you would have to look for it yourself and then send a pull request.
