### ISSUE TITLE
Turkey - Eid al-Fitr & Eid al-Adha days are incorrect and their eves are missing

### ISSUE THREAD

**Issue by seniyye** [nager/Nager.Date#600]
### Affected country

Turkey

### Affected public holiday

Eid al-Fitr First Day, Eid al-Fitr Second Day, Eid al-Fitr Third Day, Eid al-Adha First Day, Eid al-Adha Second Day, Eid al-Adha Third Day,Eid al-Adha Fourth Day 

### Source of the information

https://en.wikipedia.org/wiki/Eid_al-Fitr, https://en.wikipedia.org/wiki/Eid_al-Adha#In_the_Gregorian_calendar

### More information

Eid al-Fitr Eve and Eid al-Adha Eve are the public holidays in Turkey. That's why I request you to add these days as well.

date:"2024-04-09"localName:"Ramazan Bayramı Arifesi"name:"Eid al-Fitr Eve"countryCode:"TR"fixed:trueglobal:truecounties:nulllaunchYear:nulltypes[1]0:"Public"

date:"2024-06-15"localName:"Kurban Bayramı Arifesi"name:"Eid al-Adha Eve"countryCode:"TR"fixed:trueglobal:truecounties:nulllaunchYear:nulltypes[1]0:"Public"

**Comment by tinohager** [comment]
Hello,

thank you for your issue, we have already looked into the matter in the past. We cannot calculate the holidays automatically as they are defined by the observation of the new moon by the local religious authorities. Therefore it is not possible for us to provide these holidays.
