### ISSUE TITLE
Australia - Easter Sunday missing for some states

### ISSUE THREAD

**Issue by pdegenhardt** [nager/Nager.Date#608]
### Affected country

Australia

### Affected public holiday

Easter Sunday

### Source of the information

https://www.qld.gov.au/recreation/travel/holidays/public

### More information

All states have nominated Easter Sunday as a public holiday. E.g. Queensland link shown above.

The API incorrectly provides the date only for: ACT, NSW, VIC and WA.

It is currently national, so the simplest fix would seem to be to simply remove the 'Counties' specification.

**Comment by tinohager** [comment]
hat would mean that from 2017 the holiday should apply to the whole of australia

https://github.com/nager/Nager.Date/blob/89ece8f08542c4dd7c46b7190542dcd493b5ec69/src/Nager.Date/HolidayProviders/AustraliaHolidayProvider.cs#L231-L244

**Comment by tinohager** [comment]
I have check this source -> https://www.fairwork.gov.au/employment-conditions/public-holidays

|          | ACT | NSW | NT | QLD | SA | TAS  | VIC | WA | 
| -----  | ---- |  ----- |  --- |  ---- |  -- |  ---- | ---- |  --- |
| 2023 | ✓    |  ✓      |  ✓   |  ✓   |  -   |  -     | ✓    |  ✓   |
| 2024 | ✓    |  ✓      |  ✓   |  ✓   |  ✓  |  -     | ✓    |  ✓   |
| 2025 | ✓    |  ✓      |  ✓   |  ✓   |  ✓  |  -     | ✓    |  ✓   |

It looks in Tasmania Easter Sunday is not a public holiday.

**Comment by pdegenhardt** [comment]
Wow! I actually live in Tasmania and I had no idea. How bizarre!

**Comment by tinohager** [comment]
Hi, i have push a pull request can you check it please

**Comment by pdegenhardt** [comment]
Looks good to me. Thanks.

**Comment by tinohager** [comment]
publish a new version
