### ISSUE TITLE
Belgium holiday - Good friday is not a public holiday

### ISSUE THREAD

**Issue by Joja** [nager/Nager.Date#610]
### Affected country

Belgium

### Affected public holiday

Good Friday

### Source of the information

https://en.wikipedia.org/wiki/Public_holidays_in_Belgium

### More information

Recurring holiday marked wrong for 2024 in belgium. Good friday is coming back as being a public holiday while this should not be the case.

**Comment by tinohager** [comment]
Thank you, an error occurred during the migration of the provider. I have corrected the error.
