### ISSUE TITLE
Wrong federal states for Easter Sunday in Germany

### ISSUE THREAD

**Issue by mimenz** [nager/Nager.Date#623]
### Affected country

Germany

### Affected public holiday

Easter Sunday

### Source of the information

https://www.dgb.de/gesetzliche-feiertage-deutschland

### More information

The web service reports Easter Sunday as a public holiday for Brandenburg and Hessen.
Only Brandenburg is correct.

Sources:
- https://www.dgb.de/gesetzliche-feiertage-deutschland
- https://innen.hessen.de/buerger-staat/feiertage

BTW: Thx for the great web service!

**Comment by tinohager** [comment]
Hi Michael, thanks for the information, I'll take a look right away thanks for actively supporting this project with a sponsorship

**Comment by tinohager** [comment]
@samtrion Does it fit if we delete hessen according to the website only Brandenburg is explicitly mentioned
[PR - Missing public Holiday - Germany - Brandenburg](https://github.com/nager/Nager.Date/issues/282)

**Comment by samtrion** [comment]
Fits in principle, as already mentioned in the PR. Hesse is the only federal state that defines every Sunday as a public holiday, but there should be no problem with that.

**Comment by tinohager** [comment]
New nuget package is available. Do you use the WebApi or the Nuget package?

**Comment by mimenz** [comment]
I'm using the WebAPI from a self-hosted Docker container.
Thx for the fix!
