### ISSUE TITLE
Missing public holiday in México

### ISSUE THREAD

**Issue by Gabriglz** [nager/Nager.Date#632]
### Affected country

Mexico

### Affected public holiday

Holy Thursday, Good Friday

### Source of the information

https://www.calendario-info.es/mexico/vacaciones/viernes-santo/    https://www.calendario-info.es/mexico/vacaciones/jueves-santo/

### More information

Holy Thursday (Jueves Santo), and Good Friday (Viernes Santo) are considered holidays in Mexico, you can find more information in these links:
Holy Thursday: https://www.calendario-info.es/mexico/vacaciones/jueves-santo/
Good Friday: https://www.calendario-info.es/mexico/vacaciones/viernes-santo/
please add to the current holidays, thanks

**Comment by tinohager** [comment]
We can add this holidays with the type `Bank | School | Authorities`

**Comment by Gabriglz** [comment]
add as School type
thanks :)

**Comment by tinohager** [comment]
a new version is available, thanks
