### ISSUE TITLE
Corpus Christi is not a public holiday in every kanton (county)

### ISSUE THREAD

**Issue by SuizoSuizo** [nager/Nager.Date#634]
### Affected country

Switzerland

### Affected public holiday

Corpus Christi

### Source of the information

https://www.feiertagskalender.ch/feiertag.php?geo=3056&ft_id=38

### More information

Is public holiday in:

Appenzell Innerrhoden, Jura, Luzern, Nidwalden, Obwalden, Schwyz, Tessin, Uri, Wallis, Zug

**Comment by tinohager** [comment]
a new version is available, thanks
