### ISSUE TITLE
Is using the Nager.Date became payed .

### ISSUE THREAD

**Issue by abouroubi** [nager/Nager.Date#635]
### NuGet Package Version

2.0.0

### More information

Do we need to pay to update to v2 ?

**Comment by tinohager** [comment]
Nager.Date has long required a license to use the Nuget package. Would you like to use the project commercially?

**Comment by abouroubi** [comment]
I was using the 1.29.2 in an old side project of mine, a hobby project.
Did an update to version 1.48.0 expecting no breaking changes, but my app stopped working 😢

Anyway, I can understand that a project like this would be a payed one, it adds a lot of value.

**Comment by tinohager** [comment]
If it is a hobby project you can also use the web api, of course it requires an internet connection
https://github.com/nager/Nager.Holiday
