### ISSUE TITLE
Netherlands Liberation Day, once per 5 years a public holiday

### ISSUE THREAD

**Issue by bkampstra** [nager/Nager.Date#637]
### Affected country

Netherlands

### Affected public holiday

Liberation Day

### Source of the information

https://nl.wikipedia.org/wiki/Bevrijdingsdag

### More information

One per years (2020, 2025, 2030...) Bevrijdingsdag or Liberation Day (May 5th) is a public holiday.

**Comment by tinohager** [comment]
I cannot confirm your information, it says here on the website that it is not a public holiday.

- https://www.rijksoverheid.nl/onderwerpen/arbeidsovereenkomst-en-cao/vraag-en-antwoord/bevrijdingsdag-5-mei-vrije-dag
- https://open.overheid.nl/documenten/ronl-9f9330f50d7bd7ba0a637b6017135e1915d5509b/pdf

**Comment by tinohager** [comment]
https://www.iamexpat.nl/lifestyle/expat-events-festivals/liberation-day

> Is Liberation Day a public holiday in the Netherlands?
Liberation Day is only a public holiday in the Netherlands every five years, with businesses, [schools](https://www.iamexpat.nl/education/primary-secondary-education/school-vacations-holiday-dates) and other establishments closed. The next official Liberation Day national holiday will be on May 5, 2025.

Would this mean that it is a public holiday every 5 years. But applies to schools and authorities every year? Is there a legal text on this when it was introduced?

**Comment by tinohager** [comment]
today i send a request to the "Ministry of General Affairs" of Netherlands. I hope to get more information about the holiday here.

**Comment by tinohager** [comment]
Answer received from informatierijksoverheid.nl

> Good morning,
>
>Thank you for your e-mail. You write that you are looking for the ruleset of Liberation day in the Netherlands. You would like to know and confirm when people in the Netherlands are free on this day.
>
>I understand that you would like to confirm how this works. In the Netherlands, none of the public holidays give right on a day off by law. This is all registered in collective labour agreements. This means that the rules for this day may differ for every work sector. This means that some sectors have the day off every year on liberation day, and other sectors every 5 years. There might also be sectors that never have this day off.
>
>Information on the different sectors can be found on the page below. This page is written in Dutch, but I trust that you will be able to translate it.
>https://www.fnv.nl/werk-inkomen/vakantie-vrij-verlof/bevrijdingsdag-vrije-dag#/
>
>I trust that this is sufficient information on this topic. Have a nice day.

**Comment by twl9** [comment]
@tinohager I can confirm the information received is right. So this is not a bug
