### ISSUE TITLE
Greece - Labour Day

### ISSUE THREAD

**Issue by janez33** [nager/Nager.Date#640]
### Affected country

Greece

### Affected public holiday

Labour Day

### Source of the information

Trust me bro https://publicholidays.gr/2024-dates/

### More information

For 2024 they've changed and moved labour day from May 1st to May 7th.

I have proof also from a greek woman
![slika](https://github.com/nager/Nager.Date/assets/4009092/1a971c39-e306-494f-a4c7-96d0ff4ea05c)

**Comment by tinohager** [comment]
The Labour Day holiday on May 1 2024 falls on a Holy Week day (Holy Wednesday) and according to the Decision No 15102 ([Government Gazette B' 1406/4.3.2024](https://www.et.gr/api/DownloadFeksApi/?fek_pdf=20240201406)) of the Ministry of Labour and Social Security, the Labour Day holiday on May 1 2024 is transferred to May 7 2024.

**Comment by tinohager** [comment]
The new version is now available
