### ISSUE TITLE
United Kingdom Early May Bank Holiday moved for VE Day

### ISSUE THREAD

**Issue by Binarytales** [nager/Nager.Date#644]
### Affected country

United Kingdom

### Affected public holiday

Early May Bank Holiday

### Source of the information

https://commonslibrary.parliament.uk/bank-holidays-how-are-they-created-and-changed/#:~:text=The%20last%20time%20the%20Early,the%20second%20Monday%20of%20May.

### More information

One time change for VE Day.

This was also done in 2020 which you already have in your data.

Sources:

- https://commonslibrary.parliament.uk/bank-holidays-how-are-they-created-and-changed
- https://www.timeanddate.com/holidays/uk/early-may-bank-holiday
- https://hansard.parliament.uk/commons/1994-07-12/debates/70964f73-e609-4c19-81aa-93f83e0efc8a/MayDayBankHoliday
- https://www.gov.uk/government/news/2020-may-bank-holiday-will-be-moved-to-mark-75th-anniversary-of-ve-day
- https://www.bbc.co.uk/news/uk-48565417

**Comment by tinohager** [comment]
Hi, I have checked your request, but I can't find any information for 2025 that confirms this at the moment
https://www.gov.uk/bank-holidays#england-and-wales

**Comment by tinohager** [comment]
I checked the website again and the holiday will probably remain in the same position for 2025

**Comment by Binarytales** [comment]
Apologies, I missed your reply from May 13th.

It looks as though I was so focused on filling out the issue form correctly and providing authorative sources that I failed to provide a crucial piece of information - the **year**! 

This issue was with reagrd to the Early May Bank Holiday for **1995**. 

The website currently says this took place on May 1st. https://date.nager.at/PublicHoliday/United-Kingdom/1995

In **1995** the date of this bank holiday **May 8th**

https://www.ukbankholidays.co.uk/year/1995
https://bimcal.uk/calendar/may-1995

I rasied this using the "Wrong public holiday" form which created it as a `bug`
