### ISSUE TITLE
LicenseKeyException: Invalid LicenseKey - As a GitHub sponsor of this project you will receive a license key, https://github.com/sponsors/nager

### ISSUE THREAD

**Issue by ys2310** [nager/Nager.Date#645]
### More information

I previously purchased license key by paying $1 per month to support the project and it was working fine.
Now, with new version of Nager ver2.2, my licenseKey doesn't work.
How can I get a new license key for ver 2.2 ?

**Comment by dmasur** [comment]
I have the same problem. What was your fix?
