### ISSUE TITLE
Brazil - Dia Nacional de Zumbi e da Consciência Negra

### ISSUE THREAD

**Issue by marco-carvalho** [nager/Nager.Date#646]
### Affected country

Brazil

### Affected public holiday

Dia Nacional de Zumbi e da Consciência Negra

### Source of the information

https://www12.senado.leg.br/noticias/materias/2023/12/22/dia-da-consciencia-negra-se-torna-feriado-nacional

### More information

https://www.anbima.com.br/feriados/fer_nacionais/2024.asp

**Comment by tinohager** [comment]
It doesn't seem to be a global holiday, it only hits a few federal states is that right?

English: Black Awareness Day

Affected States:
Alagoas, Amazonas, Amapá, São Paulo, Rio de Janeiro

**Comment by marco-carvalho** [comment]
https://www.camara.leg.br/noticias/1029291-lei-torna-feriado-nacional-o-dia-20-de-novembro-dia-nacional-de-zumbi-e-da-consciencia-negra/#:~:text=Foi%20publicada%20no%20Di%C3%A1rio%20Oficial,Zumbi%20e%20da%20Consci%C3%AAncia%20Negra. 
Law 14,759/23 was published in the Official Gazette of the Union, which makes November 20th a national holiday.
