### ISSUE TITLE
Would it be possible to add the United Arab Emirates 

### ISSUE THREAD

**Issue by MischaMag** [nager/Nager.Date#651]
### More information

Would it be possible to please add the State UAE Public holidays?
Here is an overview: https://www.expatica.com/ae/lifestyle/holidays/uae-public-holidays-75017/#overview

**Comment by tinohager** [comment]
Sorry, new countries are not on our timetable at the moment.

**Comment by MischaMag** [comment]
No worries, Thanks for the response
