### ISSUE TITLE
Switzerland - Instauration de la République de Neuchâtel

### ISSUE THREAD

**Issue by Iuri-Dias** [nager/Nager.Date#660]
### Affected country

Switzerland

### Affected public holiday

Instauration de la République de Neuchâtel

### Source of the information
https://en.wikipedia.org/wiki/Public_holidays_in_Switzerland

https://www.ne.ch/medias/evenements/1erMars/Pages/Marche-du-1er-Mars.aspx#:~:text=Comme%20le%20veut%20son%20nom,du%20Locle%20et%20de%20M%C3%B4tiers.

### More information

1st of March every year this holiday is celebrated in the canton of "Neuchâtel". CH-NE

**Comment by tinohager** [comment]
Is this really a public holiday on which people have the day off or is it more of an event attended by up to 1000 people? Are companies or schools closed on this day?

**Comment by Iuri-Dias** [comment]
Yes, in the canton of Neuchâtel (NE) its a public holiday where most people have the day off.

**Comment by tinohager** [comment]
Is there a reason I can't find anything about these sources?

- https://de.wikipedia.org/wiki/Feiertage_in_der_Schweiz
- https://de.wikipedia.org/wiki/Feiertage_in_der_Schweiz

**Comment by Iuri-Dias** [comment]
Please check under the Regionale und lokale Feiertage section

**Comment by tinohager** [comment]
English Name: Republic Day
German Name: Jahrestag der Ausrufung der Republik

**Comment by Iuri-Dias** [comment]
Thank you Tino, have a great week

**Comment by tinohager** [comment]
@Iuri-Dias can you check the PR please

**Comment by Iuri-Dias** [comment]
Done, danke schön @tinohager
