### ISSUE TITLE
Australia / Brisbane Ekka People's Day missing

### ISSUE THREAD

**Issue by Zetto12** [nager/Nager.Date#662]
### Affected country

Australia

### Affected public holiday

Ekka People's day

### Source of the information

https://www.google.com/search?q=Brisbane+Holiday&rlz=1C1FKPE_enNZ989NZ989&oq=Brisbane+Holiday&gs_lcrp=EgZjaHJvbWUyCQgAEEUYORiABDIQCAEQLhivARjHARiABBiYBTIHCAIQABiABDIHCAMQABiABDIHCAQQABiABDIHCAUQABiABDIHCAYQABiABDIWCAcQLhivARjHARiABBiYBRiZBRieBTIHCAgQABiABDIHCAkQABiABNIBCDQ0MDhqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8

### More information

![image](https://github.com/user-attachments/assets/a4105f6e-c0ad-48bd-b342-eb50309bfd33)

The list for Australia has the Ekka People's day missing which is a public Holiday in Brisbane according to Google.

**Comment by tinohager** [comment]
Check this issue https://github.com/nager/Nager.Date/issues/554
