### ISSUE TITLE
WebApi - Holiday Response "fixed" is always false

### ISSUE THREAD

**Issue by MarceloMelo1** [nager/Nager.Date#664]
### Endpoint

api/v3/publicholidays/2025/BR

### More information

All holidays are coming with the field **fixed=false**

**Comment by tinohager** [comment]
With the update to V2 of Nager.Date property `fixed` is removed. For compatibility reasons, we now always supply `false`. We have marked the property as deleted in the documentation. And marked the value as obsolete in the Api. 

Thanks for the hint
