### ISSUE TITLE
Canada - Quebec rules

### ISSUE THREAD

**Issue by j-fdion** [nager/Nager.Date#665]
### Affected country

Canada

### Affected public holiday

Easter Monday

### Source of the information

https://www.statutoryholidays.com/quebec.php

### More information

In Quebec employers can choose to give the day off either on Good Friday or Easter Monday.

Other source https://www.statutoryholidays.com/easter.php

**Comment by tinohager** [comment]
What exactly do you want us to change?

**Comment by j-fdion** [comment]
Subdivision Codes should contain QC-CA

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tinohager** [comment]
If I understand it correctly, it is not a fixed day if the employee can then choose which day he takes.

**Comment by j-fdion** [comment]
It is decided by the employer, they can either give the employee both days, monday or friday.

**Comment by tinohager** [comment]
That's exactly what I mean! In the end, it means there is no fixed day. All days are actually optional. I can't define a day that applies to everyone
