### ISSUE TITLE
Switzerland - Saints Peter and Paul

### ISSUE THREAD

**Issue by ugobe** [nager/Nager.Date#667]
### Affected country

Switzerland

### Affected public holiday

Saints Peter and Paul

### Source of the information

https://en.wikipedia.org/wiki/Public_holidays_in_Switzerland

### More information

CH-TI, June, 29th

**Comment by tinohager** [comment]
Source: https://github.com/nager/Nager.Date/blob/main/src/Nager.Date/HolidayProviders/SwitzerlandHolidayProvider.cs
