### ISSUE TITLE
API only delivery types=Public?

### ISSUE THREAD

**Issue by aromko** [nager/Nager.Date#672]
### More information

Hey there. In the docs I've found that they are several types in the response like Public, School etc. I'm interested in gettting the school holidays but it seems not to work. How can I get the school holidays from the API?

**Comment by tinohager** [comment]
The different categories do not exist for all countries. Currently we have created the possibility to create holidays from these categories.

**Comment by aromko** [comment]
Thanks @tinohager for answering. For which countries they exists?

**Comment by tinohager** [comment]
https://github.com/search?q=repo%3Anager%2FNager.Date+HolidayTypes.School&type=code

- Denmark
- Mexico
- Netherlands
- Ireland
- Greenland
