### ISSUE TITLE
Question on release 2.5.1

### ISSUE THREAD

**Issue by mimenz** [nager/Nager.Date#675]
### Endpoint

/api/v3/Version

### More information

Question: why does version 2.5.1 not appear in the Public Web API and in the latest Docker container?
Not that I need the changes - just to know.
Thanks, Michael

**Comment by tinohager** [comment]
I looked at the problem and found the error dependabot suddenly stopped updating. Now everything is running again and the new docker image should be available.

**Comment by mimenz** [comment]
Strange!
I pulled a new container - but in the docker container as well as in the public web API it still shows version 2.5.0...

**Comment by mimenz** [comment]
Docker now shows 2.5.1, Public Web is still at 2.5.0

**Comment by tinohager** [comment]
Public Web is now up to date

**Comment by mimenz** [comment]
Perfect, thanks!

**Comment by mimenz** [comment]
Hi, now it's the release 2.5.2.
Docker shows 2.5.2, check.
But the Public Web API is still at 2.5.1.

Question: it should automatically update to the lastest release - also in the Public Web API? It's not on demand?

**Comment by tinohager** [comment]
The public WebApi is always a little delayed in the deployment of updates

**Comment by mimenz** [comment]
Understood 👍
