### ISSUE TITLE
Switzerland - Holiday adjustments

### ISSUE THREAD

**Issue by tinohager** [nager/Nager.Date#683]
A customer of Nager Date has kindly compiled this information which I will include in the next few days.

[Schweizer Feiertage.pdf](https://github.com/user-attachments/files/17098224/Schweizer.Feiertage.pdf)

**Comment by tinohager** [comment]
@ugobe, @SuizoSuizo, @bsrdwild, @klamir051, @Iuri-Dias

Hello everyone, as I would like to make some changes to the Swiss holidays. I would be pleased if you could perhaps also have a look at this. 

> In Switzerland, there is a law that allows for a maximum of eight public holidays per year to be treated the same as Sundays. These holidays are determined at the cantonal level, with each canton deciding which holidays qualify.

**Comment by tinohager** [comment]
“Näfelser Fahrt” is currently being ignored

**Comment by SuizoSuizo** [comment]
Hey tino. Noch nie davon gehört 🤔

Gesendet von Proton Mail für Android

-------- Ursprüngliche Nachricht --------
Am 25.09.24 16:53 um Tino Hager schrieb :

**Comment by klamir051** [comment]
Hi Tino

I've never heard of some of this rules, especially the limit of eight public holiydas. But I'm not that deep in the public holiday game to give you a reliable answer. The PDF seems kinda trustworthy, even the sources are mentioned. I don't find any inconsistencies while skimming the table.

**Comment by tinohager** [comment]
All changes announced above have now been implemented

**Comment by tinohager** [comment]
The holiday updates now available online
https://date.nager.at/PublicHoliday/Switzerland

**Comment by klamir051** [comment]
Hi Tino

You've done some decent work here! As far as I can see, some public holidays are now listed twice, once with type 'Public', once with type 'Observance'. So far, so good, but what I don't get: why e.g. Easter Monday gets listed twice for the year 2025
```
{
	"date": "2025-04-21",
	"counties": "CH-ZH,CH-BE,CH-GL,CH-FR,CH-BS,CH-BL,CH-SH,CH-AR,CH-AI,CH-SG,CH-GR,CH-AG,CH-TG,CH-TI,CH-VD,CH-GE,CH-JU",
	"types": "Public"
},
{
	"date": "2025-04-21",
	"counties": "CH-UR,CH-SZ,CH-OW",
	"types": "Observance"
}
```
But only listed once for the year 2026 - with all cantons, like before your adjustments:
```
{
	"date": "2026-04-06",
	"counties": "CH-ZH,CH-BE,CH-LU,CH-UR,CH-SZ,CH-OW,CH-NW,CH-GL,CH-ZG,CH-FR,CH-SO,CH-BS,CH-BL,CH-SH,CH-AR,CH-AI,CH-SG,CH-GR,CH-AG,CH-TG,CH-TI,CH-VD,CH-NE,CH-GE,CH-JU",
	"types": "Public"
}
```
In 2027, Easter Monday again is listed twice, in 2023 only once. I observe the same behavior with other public holidays too, like Epiphany or St. Stephen's Day.

Am I missing something?

Best

**Comment by tinohager** [comment]
@klamir051  Does the data come from the public interface? Then it is probably still due to the cache.

**Comment by klamir051** [comment]
I queried the data via public API and with your website, e.g. https://date.nager.at/PublicHoliday/Switzerland/2026. Now everything seems aligned and public holidays of type 'Observance' occur for every year. So cache might have been rebuilt in the meantime.
