### ISSUE TITLE
Argentina - Wrong public holiday

### ISSUE THREAD

**Issue by JuanIgnacioPayo** [nager/Nager.Date#685]
### Affected country

Argentina

### Affected public holiday

many holidays

### Source of the information

 https://www.argentina.gob.ar/interior/feriados-nacionales-2024

### More information

There are many affected holidays, please check the dates with the provided official link https://www.argentina.gob.ar/interior/feriados-nacionales-2024. Thank you

**Comment by tinohager** [comment]
I am happy to correct errors, but please name specific holidays where errors exist. Then we can also fix them. But simply sending a list is unfortunately not the way we work here.

**Comment by JuanIgnacioPayo** [comment]
Hi Tino, good afternoon, thank you very much for your quick response. I
didn't specify much before because I didn't know how it worked, I
apologize. Below I will indicate the dates on which the official Argentine
government calendar differs from the holiday calendar of your API. Thank
you very much for the service you provide and the responsibility with which
you work. Monday, April 1st was a holiday bridge for tourism purposes.
Friday, June 21st was a holiday bridge for tourism purposes. August 17th
fell on a Saturday and the holiday was not moved, therefore August 19th was
not a holiday. Monday, October 14th is not a holiday, the holiday on
Saturday, October 12th was moved to Friday, October 11th. Sovereignty Day
is on November 20th but since it fell on a Wednesday, they decided to move
it to Monday, November 18th.

**Comment by tinohager** [comment]
- https://github.com/nager/Nager.Date/issues/578
- https://github.com/nager/Nager.Date/issues/577
- https://github.com/nager/Nager.Date/issues/576

**Comment by tinohager** [comment]
@JuanIgnacioPayo The public holidays should now fit better, the “tourist public holidays” would require a manual entry every year. I have not yet dealt with this.

**Comment by pmxgit** [comment]
Hello,

I want to report an issue with this Holiday API for Argentina 2024: https://date.nager.at/api/v3/PublicHolidays/2024/AR

In this API we have duplicated a holiday at February 12 for 2024

"date":"**2024-02-12**","localName":"Carnaval","name":"Carnival","countryCode":"AR","fixed":false,"global":true,"counties":null,"launchYear":null,"types":["Public"]},{"date":"**2024-02-12**","localName":"Carnaval","name":"Carnival","countryCode":"AR","fixed":false,"global":true,"counties":null,"launchYear":null,"types":["Public"]}

We have 2 days for Carnaval and they are February 12 and February 13.

I will apreciate if you can change this.

Thank you very much!

**Comment by tinohager** [comment]
@pmxgit I have revised the rules again.
