### ISSUE TITLE
Missing public holiday - Berlin 08.05.2025

### ISSUE THREAD

**Issue by Skillkiller** [nager/Nager.Date#723]
### Affected country

Germany

### Affected public holiday

Tag der Befreiung

### Source of the information

https://www.berlin.de/aktuelles/9188766-958090-einmaliger-feiertag-am-8-mai-2025.html

### More information

Berlin has added another public holiday in 2025. This is unique and equivalent to the existing public holiday Liberation Day 08.05.2020 in Berlin. This holiday is not repeated on a regular basis.

The holiday is only a public holiday in Berlin and not a national holiday.

**Comment by tinohager** [comment]
- https://github.com/nager/Nager.Date/pull/715

**Comment by tinohager** [comment]
I think we have already implemented the holiday. I don't see any errors so far?

**Comment by Skillkiller** [comment]
Yes, you're right. I didn't find the holiday on the website https://date.nager.at/PublicHoliday/Germany/2025 last night. I don't know why I didn't find it, maybe I was in the wrong year by mistake.
