### ISSUE TITLE
Add country India

### ISSUE THREAD

**Issue by prasadtelkikar** [nager/Nager.Date#75]
Need to implement provider for Indian holidays
India is know for **Unity in diversity**. you can see diversity in holidays as well. Wikipedia suggests more than 20 days as holidays based on religions, states etc. Wikipedia: [Public holidays in India](https://en.wikipedia.org/wiki/Public_holidays_in_India).

Following are the national holidays which we need to add in IndianProvider.cs. Reference: [Indian post office holiday list](https://www.indiapost.gov.in/VAS/Pages/holidays.aspx).

I categorized list into two sections.

1. Holidays with fixed date.
2. Holidays which varies in date.

**Holidays with fixed date.** All dates are in dd/MM/yyyy format

- Republic day of India. -> 26/01/2018
- Independence day of India -> 15/08/2018
- [Mahatma Gandhi birthday](https://en.wikipedia.org/wiki/Mahatma_Gandhi) -> 02/10/2018
- Christmas -> 25/12/2018

**Holidays which varies in date.** All dates are in dd/MM/yyyy format

- [Mahavir jayanti](https://en.wikipedia.org/wiki/Mahavir_Jayanti).
- [Budha's Birthday](https://en.wikipedia.org/wiki/Buddha%27s_Birthday)
- [eid ul fitr](https://en.wikipedia.org/wiki/Eid_al-Fitr)
- [Bakrid](https://en.wikipedia.org/wiki/Eid_al-Adha)
- [muharram](https://en.wikipedia.org/wiki/Muharram).
- [Dussehra](https://en.wikipedia.org/wiki/Vijayadashami).
- [Diwali](https://en.wikipedia.org/wiki/Diwali). Equation = +20 days of Dussehra.
- [Id-E-Milad](https://en.wikipedia.org/wiki/Mawlid).
- [Gurunanak's Birthday](https://en.wikipedia.org/wiki/Guru_Nanak_Gurpurab).

All holidays which are categorized into second section may vary depends upon user. 
Holidays in second categories needs some sort of algorithm to get exact date.

**Comment by prasadtelkikar** [comment]
I stared working on Indian provider, added all fixed holidays. Need to work on second section holidays.

**Comment by tinohager** [comment]
Okay thanks. I think this page is also a good reference but it's no list available, of the full year. https://www.india.gov.in/calendar?date=2018

**Comment by iamrishav** [comment]
@tinohager are you working on this issue??

**Comment by tinohager** [comment]
@iamrishav I don't have time for this at the moment.

**Comment by prasadtelkikar** [comment]
@tinohager , @iamrishav  I can work on this enhancement, but it seems pretty difficult. because dates which comes under the second category are more than first category. (Refer my first message for categories).
We do not have any logic or algorithm to implement dates from second category.

If any one of you help me to design/develop logic for holiday dates which varies every year then It would be really helpful

**Comment by tinohager** [comment]
@MaximeGenevier Are you still creating a pull request for the new India provider?

**Comment by MaximeGenevier** [comment]
> @MaximeGenevier Are you still creating a pull request for the new India provider?

@tinohager No sorry, I didn't had time to work on it anymore

**Comment by tinohager** [comment]
@MaximeGenevier Thanks for the fast feedback

**Comment by tinohager** [comment]
@iamrishav @prasadtelkikar Would any of you like to complete the work of MaximeGenevier?
